"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Çeviri verileri
const translations = {
  tr: {
    // Navbar
    'home': 'Anasayfa',
    'characters': 'Karakterler',
    'stories': 'Hikayeler',
    'gallery': 'Galeri',
    'map': 'Harita',
    'shop': 'Ürünlerimiz',
    'login': 'Giriş Yap',
    'register': 'Kayıt Ol',
    'profile': 'Profilim',
    'cart': 'Sepetim',
    'orders': 'Siparişlerim',
    'requests': 'Soru ve Taleplerim',
    'offers': 'Sana Özel Fırsatlar',
    'profile_info': 'Kullanıcı Bilgilerim',
    'reviews': 'Değerlendirmelerim',
    'favorites': 'Beğendiklerim',
    'no_favorites': 'Henüz beğendiğiniz bir ürün yok.',
    'my_reviews': 'Değerlendirmelerim',
    'no_reviews': 'Henüz bir yorumunuz yok.',
    'all_lists': 'TÜM LİSTELERİM',
    'favorite_lists': 'Favori Listelerim',
    'shopping_lists': 'Alışveriş Listelerim',
    'compare_list': 'Karşılaştırma Listem',
    'reviewed_products': 'Yorumladığım Ürünler',
    'shared_lists': 'Paylaşılan Listelerim',
    'new_list': '+ Yeni Liste',
    'create': 'Oluştur',
    'list_name_placeholder': 'Liste adı girin...',
    'lists': 'Tüm Listelerim',
    'logout': 'Çıkış Yap',
    'hello': 'Merhaba',
    'menu': 'Menüyü Aç/Kapat',
    
    // Dil seçenekleri
    'language': 'Dil',
    'turkish': 'Türkçe',
    'english': 'İngilizce',

    // Ana Sayfa
    'welcome_title': 'Orta Dünya\'ya Hoş Geldiniz',
    'welcome_subtitle': 'Yüzüklerin Efendisi\'nin büyülü dünyasına adım atın',
    'explore_button': 'Yüzüğü Keşfet',
    'explore_characters': 'Karakterleri Keşfet',
    'explore_stories': 'Hikayeleri Keşfet',
    'explore_gallery': 'Galeriyi Keşfet',
    'explore_map': 'Haritayı Keşfet',
    'explore_shop': 'Ürünleri Keşfet',
    'learn_more': 'Daha Fazla Bilgi',
    'characters_title': 'Efsanevi Karakterler',
    'characters_subtitle': 'Orta Dünya\'nın en unutulmaz kahramanları ve kötüleri',
    'good_characters': 'İyi Karakterler',
    'evil_characters': 'Kötü Karakterler',
    'stories_title': 'Destansı Hikayeler',
    'stories_subtitle': 'Orta Dünya\'nın en büyük maceraları',
    'gallery_title': 'Galeri',
    'gallery_subtitle': 'Orta Dünya\'nın en güzel görselleri',
    'map_title': 'Orta Dünya Haritası',
    'map_subtitle': 'Büyülü toprakları keşfedin',
    'shop_title': 'Ürünlerimiz',
    'shop_subtitle': 'Orta Dünya\'dan özel ürünler',
    'view_all': 'Tümünü Gör',
    'add_to_cart': 'Sepete Ekle',
    'price': 'Fiyat',
    'category': 'Kategori',
    // Shop kategorileri
    'rings': 'Yüzükler',
    'swords': 'Kılıçlar',
    'cloaks': 'Pelerinler',
    'maps': 'Haritalar',
    'figures': 'Figürler',
    'elf_jewelry': 'Elf Takıları',
    'books': 'Orta Dünya Kitapları',
    'hobbit_items': 'Hobbit Eşyaları',
    'elf_bows': 'Elf Yayları',
    'dwarf_axes': 'Cüce Baltaları',
    'nazgul_masks': 'Nazgûl Maskeleri',
    'orc_armors': 'Ork Zırhları',
    'wizard_staffs': 'Büyücü Asaları',
    'gondor_helmets': 'Gondor Miğferleri',
    'rohan_horses': 'Rohan At Figürleri',
    'posters': 'Orta Dünya Posterleri',
    'cards': 'Koleksiyon Kartları',
    'collection_figures': 'Koleksiyon Figürleri',
    'home_office': 'Ev & Ofis',
    'accessories': 'Aksesuar & Takı',
    'clothes': 'Kıyafet',
    'games_puzzles': 'Oyun & Puzzle',
    'kitchen': 'Mutfak',
    'coins_replicas': 'Koleksiyon Paraları & Replikalar',
    'plush_toys': 'Peluş & Oyuncak',
    // Shop butonları
    'buy_now': 'Satın Al',
    'checkout': 'Ödeme',
    'cart_summary': 'Sepetiniz',
    'no_cart_items': 'Sepetinizde ürün yok.',
    'total': 'Toplam',
    'card_info': 'Kart Bilgileri',
    'card_name_placeholder': 'Kart Üzerindeki İsim',
    'card_number_placeholder': 'Kart Numarası',
    'expiry_placeholder': 'AA/YY',
    'cvc_placeholder': 'CVC',
    'email_placeholder': 'E-posta',
    'address_placeholder': 'Teslimat Adresi',
    'complete_payment': 'Ödemeyi Tamamla',
    'payment_success': 'Ödeme Başarılı!',
    'payment_success_desc': 'Siparişin alındı, Orta Dünya\'ya hoş geldin! 🧙‍♂️',
    'go_home': 'Anasayfaya Dön',
    // Profil menüsü
    'orders_title': 'Siparişlerim',
    'order_number': 'Sipariş',
    'order_date': 'Tarih',
    'order_status_delivered': 'Teslim Edildi',
    'order_status_shipping': 'Kargoda',
    'order_status_preparing': 'Hazırlanıyor',
    'order_status_cancelled': 'İptal Edildi',
    'order_status_pending': 'Beklemede',
    'delivery_address': 'Teslimat Adresi',
    'total_amount': 'Toplam Tutar',
    'ordered_products': 'Sipariş Edilen Ürünler',
    'order_loading': 'Yükleniyor...',
    'order_none': 'Henüz bir siparişiniz yok.',
    'order_first_cta': 'İlk siparişinizi vermek için',
    'order_first_link': 'ürünlerimizi',
    'order_first_end': 'inceleyin.',
    'order_product_none': 'Ürün bilgisi bulunamadı.',
    'currency_try': '₺',
    'currency_usd': '$',
    'requests_title': 'Soru ve Taleplerim',
    'requests_help_title': 'Size nasıl yardımcı olabiliriz?',
    'requests_help_sub': 'Sorularınızı ve taleplerinizi buradan iletebilirsiniz.',
    'select_category': 'Kategori seçiniz',
    'category_product': 'Ürün Bilgisi',
    'category_order': 'Sipariş Durumu',
    'category_return': 'İade/Değişim',
    'category_technical': 'Teknik Destek',
    'category_suggestion': 'Öneri/Şikayet',
    'category_other': 'Diğer',
    'subject_placeholder': 'Mesajınızın konusu',
    'priority_low': 'Düşük',
    'priority_normal': 'Normal',
    'priority_high': 'Yüksek',
    'priority_urgent': 'Acil',
    'message_placeholder': 'Detaylı mesajınızı buraya yazın...',
    'send_message': 'Mesajı Gönder',
    'sending': 'Gönderiliyor...',
    'contact_info': 'İletişim Bilgileri',
    'work_hours': 'Çalışma Saatleri',
    'past_requests': 'Geçmiş Talepleriniz',
    'no_requests': 'Henüz bir soru veya talebiniz yok.',
    'topic': 'Konu',
    'your_message': 'Mesajınız',
    'reply': 'Yanıt',
    'pending': 'Beklemede',
    'answered': 'Yanıtlandı',
    'required_fields': 'Lütfen tüm zorunlu alanları doldurun.',
    'user_not_found': 'Kullanıcı bulunamadı.',
    'db_error': 'Firestore bağlantısı kurulamadı.',
    'send_success': 'Mesajınız başarıyla gönderildi! En kısa sürede size dönüş yapacağız.',
    'send_error': 'Bir hata oluştu. Lütfen tekrar deneyin.',
    // --- OFFERS PAGE ---
    'loading': 'Yükleniyor...',
    'no_offers': 'Şu anda sana özel bir fırsat yok.',
    'follow_for_offers': 'Yeni fırsatlar için bizi takip etmeye devam edin!',
    'coupon_code': 'Kupon Kodu',
    'expiry_date': 'Son Kullanım Tarihi',
    'min_amount': 'Minimum Tutar',
    'start_shopping': 'Alışverişe Başla',
    'copy_code': 'Kodu Kopyala',
    'offers_email_tip': 'Fırsatları kaçırmamak için e-posta bildirimlerini açmayı unutmayın!',
    'discount': 'İndirim',
    'shipping': 'Kargo',
    'gift': 'Hediye',
    'offer': 'Fırsat',
    // --- PROFILE PAGE ---
    'profile_tab_info': 'Üyelik Bilgilerim',
    'profile_tab_password': 'Şifre Değişikliği',
    'profile_tab_prefs': 'İletişim Tercihlerim',
    'profile_tab_addresses': 'Adreslerim',
    'profile_tab_update': 'Bilgilerimi Güncelle',
    'first_name': 'Ad',
    'last_name': 'Soyad',
    'birth_date': 'Doğum Tarihi',
    'gender_select': 'Cinsiyet (seçiniz)',
    'gender_male': 'Erkek',
    'gender_female': 'Kadın',
    'gender_other': 'Diğer',
    'phone_number': 'Telefon Numarası',
    'email_address': 'Mail Adresi',
    'profile_info_note': 'Bilgiler sadece ilk kayıt sırasında doldurulabilir. Güncellemek için "Bilgilerimi Güncelle" sekmesini kullan.',
    'address_title': 'Adres Başlığı',
    'country_turkey': 'Türkiye',
    'city': 'Şehir',
    'district': 'İlçe',
    'address_detail': 'Açık Adres',
    'add': 'Ekle',
    'adding': 'Ekleniyor...',
    'saved_addresses': 'Kayıtlı Adresler:',
    'no_addresses': 'Henüz adres eklemediniz.',
    'delete': 'Sil',
    'password': 'Şifre',
    'current_password': 'Mevcut Şifre',
    'new_password': 'Yeni Şifre',
    'checking': 'Kontrol Ediliyor...',
    'continue': 'Devam Et',
    'update': 'Güncelle',
    'updating': 'Güncelleniyor...',
    'verifying': 'Doğrulanıyor...',
    'save': 'Kaydet',
    'saving': 'Kaydediliyor...',
    'sms_channel': 'Anlık/Kısa Mesaj Kanalları',
    'email_channel': 'E-Posta',
    'phone_channel': 'Telefon Araması',
  },
  en: {
    // Navbar
    'home': 'Home',
    'characters': 'Characters',
    'stories': 'Stories',
    'gallery': 'Gallery',
    'map': 'Map',
    'shop': 'Shop',
    'login': 'Login',
    'register': 'Register',
    'profile': 'Profile',
    'cart': 'Cart',
    'orders': 'My Orders',
    'requests': 'Questions & Requests',
    'offers': 'Special Offers',
    'profile_info': 'User Info',
    'reviews': 'My Reviews',
    'favorites': 'Favorites',
    'no_favorites': 'You have not favorited any products yet.',
    'my_reviews': 'My Reviews',
    'no_reviews': 'You have not written any reviews yet.',
    'all_lists': 'ALL MY LISTS',
    'favorite_lists': 'Favorite Lists',
    'shopping_lists': 'Shopping Lists',
    'compare_list': 'Compare List',
    'reviewed_products': 'Reviewed Products',
    'shared_lists': 'Shared Lists',
    'new_list': '+ New List',
    'create': 'Create',
    'list_name_placeholder': 'Enter list name...',
    'lists': 'All Lists',
    'logout': 'Logout',
    'hello': 'Hello',
    'menu': 'Toggle Menu',
    
    // Dil seçenekleri
    'language': 'Language',
    'turkish': 'Turkish',
    'english': 'English',

    // Ana Sayfa
    'welcome_title': 'Welcome to Middle-earth',
    'welcome_subtitle': 'Step into the magical world of The Lord of the Rings',
    'explore_button': 'Explore the Ring',
    'explore_characters': 'Explore Characters',
    'explore_stories': 'Explore Stories',
    'explore_gallery': 'Explore Gallery',
    'explore_map': 'Explore the Map',
    'explore_shop': 'Explore Products',
    'learn_more': 'Learn More',
    'characters_title': 'Legendary Characters',
    'characters_subtitle': 'Middle-earth\'s most unforgettable heroes and villains',
    'good_characters': 'Good Characters',
    'evil_characters': 'Evil Characters',
    'stories_title': 'Epic Stories',
    'stories_subtitle': 'Middle-earth\'s greatest adventures',
    'gallery_title': 'Gallery',
    'gallery_subtitle': 'Middle-earth\'s most beautiful images',
    'map_title': 'Middle-earth Map',
    'map_subtitle': 'Explore the magical lands',
    'shop_title': 'Our Products',
    'shop_subtitle': 'Special products from Middle-earth',
    'view_all': 'View All',
    'add_to_cart': 'Add to Cart',
    'price': 'Price',
    'category': 'Category',
    // Shop kategorileri
    'rings': 'Rings',
    'swords': 'Swords',
    'cloaks': 'Cloaks',
    'maps': 'Maps',
    'figures': 'Figures',
    'elf_jewelry': 'Elf Jewelry',
    'books': 'Middle-earth Books',
    'hobbit_items': 'Hobbit Items',
    'elf_bows': 'Elf Bows',
    'dwarf_axes': 'Dwarf Axes',
    'nazgul_masks': 'Nazgûl Masks',
    'orc_armors': 'Orc Armors',
    'wizard_staffs': 'Wizard Staffs',
    'gondor_helmets': 'Gondor Helmets',
    'rohan_horses': 'Rohan Horse Figures',
    'posters': 'Middle-earth Posters',
    'cards': 'Collection Cards',
    'collection_figures': 'Collection Figures',
    'home_office': 'Home & Office',
    'accessories': 'Accessories & Jewelry',
    'clothes': 'Clothes',
    'games_puzzles': 'Games & Puzzles',
    'kitchen': 'Kitchen',
    'coins_replicas': 'Coins & Replicas',
    'plush_toys': 'Plush & Toys',
    // Shop butonları
    'buy_now': 'Buy Now',
    'checkout': 'Checkout',
    'cart_summary': 'Your Cart',
    'no_cart_items': 'Your cart is empty.',
    'total': 'Total',
    'card_info': 'Card Information',
    'card_name_placeholder': 'Name on Card',
    'card_number_placeholder': 'Card Number',
    'expiry_placeholder': 'MM/YY',
    'cvc_placeholder': 'CVC',
    'email_placeholder': 'Email',
    'address_placeholder': 'Shipping Address',
    'complete_payment': 'Complete Payment',
    'payment_success': 'Payment Successful!',
    'payment_success_desc': 'Your order has been received, welcome to Middle-earth! 🧙‍♂️',
    'go_home': 'Return to Home',
    // Profil menüsü
    'orders_title': 'My Orders',
    'order_number': 'Order',
    'order_date': 'Date',
    'order_status_delivered': 'Delivered',
    'order_status_shipping': 'Shipped',
    'order_status_preparing': 'Preparing',
    'order_status_cancelled': 'Cancelled',
    'order_status_pending': 'Pending',
    'delivery_address': 'Delivery Address',
    'total_amount': 'Total Amount',
    'ordered_products': 'Ordered Products',
    'order_loading': 'Loading...',
    'order_none': 'You have no orders yet.',
    'order_first_cta': 'To place your first order,',
    'order_first_link': 'check our products',
    'order_first_end': '.',
    'order_product_none': 'No product information found.',
    'currency_try': '₺',
    'currency_usd': '$',
    'requests_title': 'Questions & Requests',
    'requests_help_title': 'How can we help you?',
    'requests_help_sub': 'You can send your questions and requests here.',
    'select_category': 'Select category',
    'category_product': 'Product Info',
    'category_order': 'Order Status',
    'category_return': 'Return/Exchange',
    'category_technical': 'Technical Support',
    'category_suggestion': 'Suggestion/Complaint',
    'category_other': 'Other',
    'subject_placeholder': 'Subject of your message',
    'priority_low': 'Low',
    'priority_normal': 'Normal',
    'priority_high': 'High',
    'priority_urgent': 'Urgent',
    'message_placeholder': 'Write your detailed message here...',
    'send_message': 'Send Message',
    'sending': 'Sending...',
    'contact_info': 'Contact Information',
    'work_hours': 'Working Hours',
    'past_requests': 'Your Past Requests',
    'no_requests': 'You have no questions or requests yet.',
    'topic': 'Topic',
    'your_message': 'Your Message',
    'reply': 'Reply',
    'pending': 'Pending',
    'answered': 'Answered',
    'required_fields': 'Please fill in all required fields.',
    'user_not_found': 'User not found.',
    'db_error': 'Could not connect to Firestore.',
    'send_success': 'Your message has been sent successfully! We will get back to you as soon as possible.',
    'send_error': 'An error occurred. Please try again.',
    // --- OFFERS PAGE ---
    'loading': 'Loading...',
    'no_offers': 'There are no special offers for you at the moment.',
    'follow_for_offers': 'Keep following us for new offers!',
    'coupon_code': 'Coupon Code',
    'expiry_date': 'Expiry Date',
    'min_amount': 'Minimum Amount',
    'start_shopping': 'Start Shopping',
    'copy_code': 'Copy Code',
    'offers_email_tip': 'Don\'t forget to enable email notifications to not miss any offers!',
    'discount': 'Discount',
    'shipping': 'Shipping',
    'gift': 'Gift',
    'offer': 'Offer',
    // --- PROFILE PAGE ---
    'profile_tab_info': 'Membership Info',
    'profile_tab_password': 'Change Password',
    'profile_tab_prefs': 'Contact Preferences',
    'profile_tab_addresses': 'My Addresses',
    'profile_tab_update': 'Update Info',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'birth_date': 'Birth Date',
    'gender_select': 'Gender (select)',
    'gender_male': 'Male',
    'gender_female': 'Female',
    'gender_other': 'Other',
    'phone_number': 'Phone Number',
    'email_address': 'Email Address',
    'profile_info_note': 'Info can only be filled during registration. Use the "Update Info" tab to update.',
    'address_title': 'Address Title',
    'country_turkey': 'Turkey',
    'city': 'City',
    'district': 'District',
    'address_detail': 'Full Address',
    'add': 'Add',
    'adding': 'Adding...',
    'saved_addresses': 'Saved Addresses:',
    'no_addresses': 'You have not added any address yet.',
    'delete': 'Delete',
    'password': 'Password',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'checking': 'Checking...',
    'continue': 'Continue',
    'update': 'Update',
    'updating': 'Updating...',
    'verifying': 'Verifying...',
    'save': 'Save',
    'saving': 'Saving...',
    'sms_channel': 'SMS Channels',
    'email_channel': 'E-mail',
    'phone_channel': 'Phone Call',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('tr');

  useEffect(() => {
    // LocalStorage'dan dil tercihini al
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'tr' || savedLanguage === 'en')) {
        setLanguageState(savedLanguage);
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
      // HTML lang attribute'unu güncelle
      document.documentElement.lang = lang;
    }
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
} 