"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Çeviri verileri
const translations = {
  tr: {
    // Navbar
    'home': 'Anasayfa',
    'characters': 'Karakterler',
    'stories': 'Hikayeler',
    'gallery': 'Galeri',
    'map': 'Harita',
    'shop': 'Ürünlerimiz',
    'login': 'Giriş Yap',
    'register': 'Kayıt Ol',
    'profile': 'Profilim',
    'cart': 'Sepetim',
    'orders': 'Siparişlerim',
    'requests': 'Soru ve Taleplerim',
    'offers': 'Sana Özel Fırsatlar',
    'profile_info': 'Kullanıcı Bilgilerim',
    'reviews': 'Değerlendirmelerim',
    'favorites': 'Beğendiklerim',
    'no_favorites': 'Henüz beğendiğiniz bir ürün yok.',
    'my_reviews': 'Değerlendirmelerim',
    'no_reviews': 'Henüz bir yorumunuz yok.',
    'all_lists': 'TÜM LİSTELERİM',
    'favorite_lists': 'Favori Listelerim',
    'shopping_lists': 'Alışveriş Listelerim',
    'compare_list': 'Karşılaştırma Listem',
    'reviewed_products': 'Yorumladığım Ürünler',
    'shared_lists': 'Paylaşılan Listelerim',
    'new_list': '+ Yeni Liste',
    'create': 'Oluştur',
    'list_name_placeholder': 'Liste adı girin...',
    'lists': 'Tüm Listelerim',
    'logout': 'Çıkış Yap',
    'hello': 'Merhaba',
    'menu': 'Menüyü Aç/Kapat',
    
    // Dil seçenekleri
    'language': 'Dil',
    'turkish': 'Türkçe',
    'english': 'İngilizce',

    // Ana Sayfa
    'welcome_title': 'Orta Dünya\'ya Hoş Geldiniz',
    'welcome_subtitle': 'Yüzüklerin Efendisi\'nin büyülü dünyasına adım atın',
    'explore_button': 'Yüzüğü Keşfet',
    'explore_characters': 'Karakterleri Keşfet',
    'explore_stories': 'Hikayeleri Keşfet',
    'explore_gallery': 'Galeriyi Keşfet',
    'explore_map': 'Haritayı Keşfet',
    'explore_shop': 'Ürünleri Keşfet',
    'learn_more': 'Daha Fazla Bilgi',
    'characters_title': 'Efsanevi Karakterler',
    'characters_subtitle': 'Orta Dünya\'nın en unutulmaz kahramanları ve kötüleri',
    'good_characters': 'İyi Karakterler',
    'evil_characters': 'Kötü Karakterler',
    'stories_title': 'Destansı Hikayeler',
    'stories_subtitle': 'Orta Dünya\'nın en büyük maceraları',
    'gallery_title': 'Galeri',
    'gallery_subtitle': 'Orta Dünya\'nın en güzel görselleri',
    // Galeri sayfası
    'gallery_page_title': 'Galeri',
    'fellowship': 'Yüzük Kardeşliği',
    'shire': 'Shire',
    'rivendell': 'Rivendell',
    'rohan': 'Rohan',
    'gondor': 'Gondor',
    'mordor': 'Mordor',
    'mount_doom': 'Mount Doom',
    'helms_deep': 'Helm\'s Deep',
    'galadriel': 'Galadriel',
    // Yüzük Kardeşliği sayfası
    'fellowship_page_title': 'Yüzük Kardeşliği',
    'fellowship_quote': 'Yüzük Arkadaşlığı Dokuz olmalı; ve Dokuz Yürüyüşçü kötülük eden Dokuz Binici\'ye karşı kurulmalı',
    'fellowship_quote_author': 'Elrond',
    'fellowship_description': 'Yüzük Arkadaşlığı olarak da bilinen Yüzük Kardeşliği, Yüzük Savaşı sırasında Özgür Halkların dokuz üyesinden oluşmuştur. Amacı, Tek Yüzüğü Mordor\'a, yok edilebileceği tek yere götürmekti.',
    'view_members': 'Üyeleri Gör',
    'members_title': 'Üyeleri',
    'age_label': 'Yaş',
    'history_title': 'Tarih',
    'return_home': 'Ana Sayfaya Dön',
    // Yüzük Kardeşliği üyeleri
    'gandalf_name': 'Gandalf',
    'gandalf_desc': 'Valar tarafından Orta Dünya\'ya gönderilen Büyücülerden biri. Kardeşliğin lideriydi.',
    'aragorn_name': 'Aragorn',
    'aragorn_desc': 'Arathorn oğlu. Dúnedain\'in Şefi ve Gondor ve Arnor tahtının son varisi. Gandalf\'ın kaybından sonra Kardeşliği yönetti.',
    'boromir_name': 'Boromir',
    'boromir_desc': 'Denethor oğlu. Gondor kaptanı/generali ve bir sonraki sıradaki Gondor Hükümdar Vekilharcı.',
    'legolas_name': 'Legolas',
    'legolas_desc': 'Mirkwood\'lu Thranduil\'in oğlu. Mirkwood Elfleri\'nin elçisi.',
    'gimli_name': 'Gimli',
    'gimli_desc': 'Glóin oğlu. Yalnız Dağ\'dan bir cüce.',
    'frodo_name': 'Frodo Baggins',
    'frodo_desc': 'Shire\'dan bir hobbit. Tek Yüzüğü taşıyacak kişi olarak seçildi.',
    'sam_name': 'Samwise Gamgee',
    'sam_desc': 'Bir hobbit, Frodo\'nun bahçivanı, uşağı ve yakın arkadaşı.',
    'merry_name': 'Meriadoc "Merry" Brandybuck',
    'merry_desc': 'Bir hobbit, Frodo\'nun kuzeni, Pippin\'in en iyi arkadaşı.',
    'pippin_name': 'Peregrin "Pippin" Took',
    'pippin_desc': 'Bir hobbit, Frodo\'nun kuzeni, kardeşliğin en genç üyesi.',
    // Tarih bölümü çevirileri
    'fellowship_history_1': 'Yüzük kardeşliği, Tek Yüzüğü yok etmek amacıyla Rivendell\'de kuruldu ve bunu yapmanın tek yolu onu Kıyamet Çatlakları\'na atmaktı. Sauron\'un dokuz binicisine karşı Frodo\'nun Yüzük Taşıyıcısı olarak, Gandalf\'ın ise lider olarak dokuz yürüyüşçüden oluşması gerektiğine karar verildi.',
    'fellowship_history_2': 'Amaç Elrond\'un Divanı tarafından belirlenmesine rağmen, bunun nasıl, hangi şekilde ve hangi yolla yapılabileceği karara bağlanmadı; bu tür detaylar Kardeşliğin takdirine bırakılmıştır. Sonuç olarak, Kardeşlik, ayrıntılı bir plan olmadan başladı. Bir seçenek doğrudan Hüküm Dağı\'na gitmek, diğeri Boromir\'in babası Denethor II\'den yardım istemekti.',
    'fellowship_history_3': 'Doğu\'ya nasıl ulaşılacağı bir problemdi. Rivendell\'den güneye geçtikten sonra, Hollin\'e varışlarında crebain ile karşılaştılar. Saruman tarafından casus olarak kullanılmasından korkan Kardeşlik, bütün gününü kamp ateşi olmadan saklanarak geçirdi.',
    'fellowship_history_4': 'Dumanlı Dağlar\'ı geçmek zorunda kaldıklarında; Boromir, Rohan Boşluğu\'nu önerdi, Gandalf Moria\'dan geçmek için ısrar etti, ancak Aragorn, Kızılboyuz Geçidi\'nin daha güvenli olacağını düşünüyordu. Ancak fırtınayı geçmek için boşuna uğraştıktan sonra, Gandalf\'ın seçeneğini takip ettiler.',
    'fellowship_history_5': 'Kurtlarla ve Sudaki Gözcü\'yle kavga ettikten sonra, Durin Kapıları\'nı açıp Moria\'ya girmeyi başardılar. Orada yıllar önce Balin\'in Kolonisi\'ni ele geçiren Orkları buldular. Ayrıca, ilk etapta Moria\'yı mahveden Durin\'in Felaketi\'ni de gördüler.',
    'fellowship_history_6': 'Gandalf onları zaman kazanmak için, Khazad-dûm Köprüsü\'nü imha etti ve her iki Maiar da uçuruma düşerken diğerleri ışığa ulaştı; Aragorn, grubun başına getirildi ve bir sonraki durakları, Lothlórien\'in elf efendileri Galadriel ve Celeborn ile buluşmaktı.',
    'fellowship_history_7': 'Dört hafta boyunca orada kaldılar, dinlenip, planları ve rotaları için kafa yordular. Ayrılırlarken, elfler onlara çeşitli hediyeler ve Anduin\'e yelken açmaları için bot verdiler.',
    'fellowship_history_8': 'Bu arada, Sauron\'a hizmet eden Saruman, Yüzüğü taşıyan buçukluğu yakalamak ve onu Isengard\'a getirmek için bir Uruk-hai grubu gönderdi. Frodo sadece birisinin onları takip ettiğini değil, aynı zamanda Yüzüğün bazı parti üyeleri üzerinde, özellikle de Boromir\'de kötü niyetli bir etkiye sahip olduğunu fark etmeye başladı.',
    'fellowship_history_9': 'Argonath\'tan geçtikten sonra yüzüğü ondan almaya çalışan oydu. Bu sırada Frodo, ondan kaçmak için yüzüğü taktı, ama Sam onu takip etti. Kardeşliğin geri kalanı Yüzük Taşıyıcı\'yı bulmaya çalışırken orklar tarafından saldırıya uğradı. Başka bir buçukluk görmeyen Orklar Merry ve Pippin\'i yakalamayı başardılar ve onları korumaya çalışan Boromir\'i öldürdüler.',
    'fellowship_history_10': 'Ve böylece, Kardeşlil bozuldu, fakat henüz dağılmadı. Sam, Mordor\'a yalnız başına gitmeye karar veren Frodo\'yu Emyn Muil\'den aşağıya doğru takip etti. Gimli ve Legolas\'lı Aragorn ("Üç Avcı"), Orkları Rohan\'a kadar takip etmeye ve Pippin ve Merry\'yi kurtarmaya karar verdi. Hepsinen habersiz, Gandalf dirildi ve onlardan sonra Lothlórien\'i ziyaret etti.',
    'fellowship_history_11': 'Birçok maceradan sonra, geri kalan sekiz kardeşlik üyesi Sauron\'un çöküşünden sonra tekrar bir araya geldi. Kral Théoden\'in cenazesi Minas Tirith\'ten yola çıktığında, sekiz yoldaş Orthanc\'ta Ağaçsakal ile buluşuncaya kadar beraber yolculuk yaptılar. Orada Gimli ve Legolas, Fangorn Ormanı\'nın derin bölgelerini kendi evlerine giderken ziyaret etmek için yola çıktı ve Aragorn, Yüzük Kardeşliğinin en sonunda sona erdiğini açıkladı.',
    // Shire sayfası
    'shire_page_title': 'Shire',
    'shire_quote': 'Shire\'da her şey yeşil ve güzel, ve hobbitler barış içinde yaşar',
    'shire_quote_author': 'Bilbo Baggins',
    'shire_description': 'Shire, Orta Dünya\'nın kuzeybatısında yer alan, hobbitlerin anavatanıdır. Yeşil tepeler, yemyeşil çayırlar ve huzurlu hobbit delikleriyle ünlü bu bölge, barış ve refahın simgesidir.',
    'explore_locations': 'Yerleri Keşfet',
    'explore_cities': 'Şehirleri Keşfet',
    'learn_culture': 'Kültürü Öğren',
    'learn_forces': 'Güçleri Öğren',
    'important_locations': 'Önemli Yerler',
    'hobbit_culture': 'Hobbit Kültürü',
    'shire_history': 'Shire\'ın Tarihi',
    // Shire yerleri
    'hobbiton_name': 'Hobbiton',
    'hobbiton_desc': 'Shire\'ın kalbi, hobbitlerin en büyük yerleşim yeri. Yeşil tepeler ve hobbit delikleriyle ünlü.',
    'bag_end_name': 'Bag End',
    'bag_end_desc': 'Baggins ailesinin evi, Bilbo ve Frodo\'nun yaşadığı yer. Shire\'ın en güzel hobbit deliği.',
    'green_dragon_name': 'Green Dragon Inn',
    'green_dragon_desc': 'Hobbitlerin toplandığı meşhur han. Bira ve yemekleriyle ünlü.',
    'brandy_hall_name': 'Brandy Hall',
    'brandy_hall_desc': 'Brandybuck ailesinin büyük evi. Buckland\'da yer alır.',
    'tookland_name': 'Tookland',
    'tookland_desc': 'Took ailesinin toprakları. Shire\'ın en batı bölgesi.',
    'michel_delving_name': 'Michel Delving',
    'michel_delving_desc': 'Shire\'ın başkenti. Büyük Smials\'da Shire-moot toplanır.',
    // Hobbit kültürü
    'hobbit_lifestyle_title': 'Hobbit Yaşam Tarzı',
    'hobbit_lifestyle_desc': 'Hobbitler sakin, barışçıl ve toprağa bağlı bir halktır. Yemek yemeyi, bira içmeyi ve bahçıvanlığı çok severler.',
    'hobbit_holes_title': 'Hobbit Delikleri',
    'hobbit_holes_desc': 'Hobbitler yuvarlak kapılı, toprağa gömülü evlerde yaşar. Bu evler hem sıcak hem de güvenlidir.',
    'shire_calendar_title': 'Shire Takvimi',
    'shire_calendar_desc': 'Hobbitler kendi takvimlerini kullanır. Yılbaşı 25 Mart\'ta, yıl ortası 22 Haziran\'da kutlanır.',
    'hobbit_cuisine_title': 'Hobbit Mutfağı',
    'hobbit_cuisine_desc': 'Günde 6 öğün yemek yerler: Kahvaltı, ikinci kahvaltı, onbirler, öğle yemeği, çay ve akşam yemeği.',
    // Shire tarihi
    'shire_history_1': 'Shire, Üçüncü Çağ\'ın 1601. yılında, hobbitlerin Eriador\'a yerleşmesiyle kuruldu. İlk yerleşimciler, Bree\'den gelen Marcho ve Blanco adlı iki kardeşti. Gondor Kralı Argeleb II, hobbitlere Shire\'ı verdi ve onlara tam özerklik tanıdı.',
    'shire_history_2': 'Shire dört bölgeye ayrılır: Kuzey, Güney, Doğu ve Batı Farthing. Her bölgenin kendi özellikleri ve hobbit aileleri vardır. En önemli aileler Baggins, Took, Brandybuck ve Gamgee\'dir.',
    'shire_history_3': 'Hobbitler, Shire\'da barış içinde yaşarlar ve dış dünyayla çok az ilişki kurarlar. Kendi yönetim sistemleri vardır: Thain (askeri lider), Mayor (sivil yönetici) ve Shirriffs (kolluk kuvveti).',
    'shire_history_4': 'Shire\'ın en ünlü sakinleri arasında Bilbo Baggins (Yüzüklerin Efendisi\'nin başlangıcındaki ana karakter) ve onun yeğeni Frodo Baggins (Yüzük Taşıyıcısı) bulunur. Bu iki hobbit, Orta Dünya\'nın kaderini değiştiren maceralara atılmıştır.',
    'shire_history_5': 'Shire, Yüzük Savaşı sırasında Saruman tarafından işgal edildi ve büyük zarar gördü. Ancak savaştan sonra, Aragorn\'un emriyle Shire yeniden inşa edildi ve hobbitler eski huzurlu yaşamlarına döndüler.',
    'shire_history_6': 'Günümüzde Shire, Orta Dünya\'nın en huzurlu ve refah içindeki bölgesidir. Hobbitler, yeşil tepelerde, yuvarlak kapılı evlerinde barış içinde yaşamaya devam ederler.',
    // Rivendell sayfası
    'rivendell_page_title': 'Rivendell',
    'rivendell_quote': 'Rivendell\'de huzur ve bilgelik bulunur, burada zaman durur',
    'rivendell_quote_author': 'Elrond',
    'rivendell_description': 'Rivendell (Ayrıkvadi), Orta Dünya\'nın en güzel ve huzurlu yerlerinden biridir. Elf Lord\'u Elrond\'un yönettiği bu gizli vadi, yaralıların iyileştiği, bilgelerin toplandığı ve yolcuların dinlendiği bir sığınaktır.',
    'explore_features': 'Özellikleri Keşfet',
    'elf_culture': 'Elf Kültürü',
    'rivendell_features': 'Rivendell\'in Özellikleri',
    'rivendell_history': 'Rivendell\'in Tarihi',
    // Rivendell özellikleri
    'elronds_house_name': 'Elrond\'un Evi',
    'elronds_house_desc': 'Rivendell\'in kalbi, Elrond\'un yaşadığı ve misafirlerini ağırladığı görkemli ev.',
    'waterfalls_name': 'Şelaleler',
    'waterfalls_desc': 'Dağlardan aşağıya akan muhteşem şelaleler, Rivendell\'e büyülü bir atmosfer katar.',
    'bridges_name': 'Köprüler',
    'bridges_desc': 'Zarif kemerli taş köprüler, şehrin farklı bölümlerini birbirine bağlar.',
    'library_name': 'Kütüphane',
    'library_desc': 'Antik bilgilerin saklandığı, Elf bilgeliğinin merkezi.',
    'gardens_name': 'Bahçeler',
    'gardens_desc': 'Yemyeşil bahçeler ve çiçeklerle dolu, huzur veren mekanlar.',
    'healing_rooms_name': 'Şifa Odaları',
    'healing_rooms_desc': 'Elf şifacılarının çalıştığı, yaralıları iyileştiren özel odalar.',
    // Elf kültürü
    'elf_wisdom_title': 'Elf Bilgeliği',
    'elf_wisdom_desc': 'Elfler binlerce yıllık bilgiye sahiptir. Rivendell, Orta Dünya\'nın en büyük bilgelik merkezlerinden biridir.',
    'elf_architecture_title': 'Elf Mimarisı',
    'elf_architecture_desc': 'Zarif, organik hatlar ve doğayla uyumlu tasarım. Rivendell\'in binaları hem güzel hem de işlevseldir.',
    'elf_art_title': 'Elf Sanatı',
    'elf_art_desc': 'Müzik, şiir ve görsel sanatlarda ustalaşmış elfler, güzelliği her şeyin üstünde tutar.',
    'immortality_title': 'Ölümsüzlük',
    'immortality_desc': 'Elfler ölümsüzdür ve zamanın geçişini farklı algılar. Bu onlara benzersiz bir perspektif verir.',
    // Rivendell tarihi
    'rivendell_history_1': 'Rivendell, İkinci Çağ\'ın sonlarında, Elrond tarafından kuruldu. Elrond, Sauron\'un güçlerine karşı savaşan Son İttifak\'ın bir parçasıydı ve savaştan sonra bu gizli vadide bir sığınak inşa etti.',
    'rivendell_history_2': 'Rivendell, zamanla Orta Dünya\'nın en önemli bilgelik merkezlerinden biri haline geldi. Burada antik kitaplar saklanır, bilgeler toplanır ve yaralılar iyileştirilir. Elrond\'un evi, tüm ırklardan misafirleri ağırlar.',
    
    // Galadriel sayfası
    'galadriel_page_title': 'Galadriel',
    'galadriel_quote': 'Lothlórien\'in Kraliçesi - Nenya\'nın Taşıyıcısı',
    'galadriel_quote_author': 'Celeborn\'un Eşi',
    'galadriel_description': 'Galadriel, Orta Dünya\'nın en güçlü elf kadınıdır. Lothlórien\'in kraliçesi olarak, Nenya yüzüğünün taşıyıcısı ve Valinor\'dan gelen son Noldor\'dan biridir.',
    'history_and_importance': 'Tarih ve Önem',
    'power_and_magic': 'Güç ve Büyü',
    // Galadriel tarihi
    'galadriel_history_1': 'Galadriel, Valinor\'dan Orta Dünya\'ya gelen son Noldor\'dan biridir. Fëanor\'un isyanına katılmış ve Valinor\'dan ayrılmıştır. Binlerce yıl boyunca Orta Dünya\'da yaşamıştır.',
    'galadriel_history_2': 'İkinci Çağ\'da, Galadriel ve eşi Celeborn, Lothlórien\'i kurmuşlardır. Bu krallık, Orta Dünya\'nın en güzel ve gizemli yerlerinden biri haline gelmiştir.',
    'galadriel_history_3': 'Galadriel, Nenya yüzüğünün taşıyıcısıdır. Bu yüzük, Lothlórien\'i korur ve zamanın etkilerini yavaşlatır. Galadriel\'in gücü, krallığının güvenliği için kullanılır.',
    // Galadriel güçleri
    'nenya_ring_title': 'Nenya Yüzüğü',
    'nenya_ring_desc': 'Galadriel, Nenya yüzüğünü taşır. Bu yüzük, Lothlórien\'i korur ve zamanın etkilerini yavaşlatır. Yüzük, su ve elmas taşından yapılmıştır.',
    'magic_power_title': 'Büyü Gücü',
    'magic_power_desc': 'Galadriel, Orta Dünya\'nın en güçlü elf kadınıdır. Büyü gücü, geleceği görebilme ve düşmanlarını korkutma yeteneği vardır.',
    'lothlorien_protector_title': 'Lothlórien\'in Koruyucusu',
    'lothlorien_protector_desc': 'Galadriel\'in gücü, Lothlórien\'i korur. Krallık, onun büyüsü sayesinde gizli ve güvenli kalır. Düşmanlar, krallığa giremez.',
    // Önemli olaylar
    'important_events_title': 'Önemli Olaylar',
    'departure_from_valinor_title': 'Valinor\'dan Ayrılış',
    'departure_from_valinor_desc': 'Galadriel, Fëanor\'un isyanına katılarak Valinor\'dan ayrıldı. Orta Dünya\'ya gelerek binlerce yıl boyunca burada yaşadı.',
    'lothlorien_foundation_title': 'Lothlórien\'in Kuruluşu',
    'lothlorien_foundation_desc': 'İkinci Çağ\'da, Galadriel ve Celeborn Lothlórien\'i kurdular. Bu krallık, Orta Dünya\'nın en güzel yerlerinden biri oldu.',
    'fellowship_hosting_title': 'Yüzük Kardeşliği',
    'fellowship_hosting_desc': 'Galadriel, Yüzük Kardeşliği\'ne Lothlórien\'de ev sahipliği yaptı. Onlara hediyeler verdi ve yolculuklarına devam etmelerine yardım etti.',
    // Lothlórien
    'lothlorien_title': 'Lothlórien',
    'golden_forest_title': 'Altın Orman',
    'golden_forest_desc_1': 'Lothlórien, mallorn ağaçlarıyla kaplı altın bir ormandır. Bu ağaçlar, Galadriel\'in büyüsü sayesinde her zaman altın yapraklarıyla parlar.',
    'golden_forest_desc_2': 'Orman, zamanın etkilerinden korunmuştur ve içinde yaşayan elfler için güvenli bir sığınaktır.',
    'caras_galadhon_title': 'Caras Galadhon',
    'caras_galadhon_desc_1': 'Lothlórien\'in başkenti olan Caras Galadhon, mallorn ağaçları üzerine kurulmuş bir şehirdir. Galadriel ve Celeborn burada yaşar ve krallığı yönetir.',
    'caras_galadhon_desc_2': 'Şehir, Galadriel\'in büyüsü sayesinde gizli kalır ve düşmanlar tarafından görülemez.',
    'rivendell_history_3': 'Rivendell\'in en önemli özelliklerinden biri, zamanın burada farklı akmasıdır. Vadi, dış dünyadan izole edilmiş ve kendi huzurlu atmosferini korur. Bu, yaralıların iyileşmesi ve yolcuların dinlenmesi için ideal bir ortam yaratır.',
    'rivendell_history_4': 'Rivendell, Yüzük Savaşı sırasında kritik bir rol oynadı. Burada Yüzük Kardeşliği kuruldu ve Frodo\'nun yarası iyileştirildi. Elrond\'un Divanı, Orta Dünya\'nın kaderini değiştiren kararları aldı.',
    'rivendell_history_5': 'Rivendell\'in mimarisi, Elf sanatının en güzel örneklerinden biridir. Zarif kemerler, zarif süslemeler ve doğayla uyumlu tasarım, burayı Orta Dünya\'nın en güzel yerlerinden biri yapar.',
    'rivendell_history_6': 'Günümüzde Rivendell, hala Elrond\'un yönetimi altında, Orta Dünya\'nın en huzurlu ve güvenli yerlerinden biri olarak hizmet vermektedir. Burada zaman durur ve bilgelik sonsuza dek korunur.',
    // Rohan sayfası
    'rohan_page_title': 'Rohan',
    'rohan_quote': 'Rohan\'da atlar özgürce koşar ve savaşçılar cesurca savaşır',
    'rohan_quote_author': 'Théoden Kral',
    'rohan_description': 'Rohan, Orta Dünya\'nın kuzeyinde yer alan, atlı savaşçılarıyla ünlü güçlü bir krallıktır. Geniş çayırları, cesur savaşçıları ve özgür ruhlu halkıyla tanınır.',
    'rohan_locations': 'Önemli Yerler',
    'rohan_culture': 'Rohan Kültürü',
    'rohan_history': 'Rohan\'ın Tarihi',
    // Rohan yerleri
    'edoras_name': 'Edoras',
    'edoras_desc': 'Rohan\'ın başkenti, Meduseld (Altın Salon) ile ünlü. Tepede kurulu görkemli şehir.',
    'meduseld_name': 'Meduseld',
    'meduseld_desc': 'Rohan krallarının sarayı. Altın Salon olarak bilinen görkemli yapı.',
    'helms_deep_name': 'Helm\'s Deep',
    'helms_deep_desc': 'Rohan\'ın en güçlü kalesi. Hornburg olarak da bilinir.',
    'aldburg_name': 'Aldburg',
    'aldburg_desc': 'Eorl\'un eski başkenti. Rohan\'ın ilk yerleşim yeri.',
    'westfold_name': 'Westfold',
    'westfold_desc': 'Rohan\'ın batı bölgesi. Geniş çayırlar ve at sürüleriyle ünlü.',
    'eastfold_name': 'Eastfold',
    'eastfold_desc': 'Rohan\'ın doğu bölgesi. Anduin nehri boyunca uzanır.',
    // Rohan kültürü
    'horse_culture_title': 'Atlı Kültürü',
    'horse_culture_desc': 'Rohanlılar atlarla güçlü bir bağ kurmuştur. At sürücülüğünde ustalaşmışlardır.',
    'warrior_spirit_title': 'Savaşçı Ruhu',
    'warrior_spirit_desc': 'Rohanlılar cesur savaşçılardır. Süvari birlikleri Orta Dünya\'nın en güçlüleridir.',
    'meadow_life_title': 'Çayır Yaşamı',
    'meadow_life_desc': 'Geniş çayırlarda yaşayan Rohanlılar, doğayla uyumlu bir yaşam sürer.',
    'heroism_tradition_title': 'Kahramanlık Geleneği',
    'heroism_tradition_desc': 'Rohan\'da kahramanlık ve onur en yüksek değerlerdir.',
    // Rohan tarihi
    'rohan_history_1': 'Rohan, Üçüncü Çağ\'ın 2510. yılında kuruldu. Eorl the Young, Gondor\'a yardım etmek için kuzeyden geldi ve Calenardhon topraklarını aldı. Bu topraklar artık Rohan olarak bilinir.',
    'rohan_history_2': 'Rohanlılar, Eorl\'un soyundan gelen krallar tarafından yönetilir. Başkentleri Edoras\'tır ve en önemli yapıları Meduseld (Altın Salon) olarak bilinen krallık sarayıdır.',
    'rohan_history_3': 'Rohan, atlı savaşçılarıyla ünlüdür. Süvari birlikleri, Orta Dünya\'nın en güçlü askeri güçlerinden biridir. Rohanlılar, atlarla güçlü bir bağ kurmuş ve at sürücülüğünde ustalaşmıştır.',
    'rohan_history_4': 'Rohan, Yüzük Savaşı sırasında kritik bir rol oynadı. Helm\'s Deep Savaşı\'nda Saruman\'ın ordularına karşı büyük bir direniş gösterdi. Théoden Kral\'ın liderliği altında, Rohan Gondor\'a yardım etti ve Pelennor Savaşı\'nda büyük kahramanlık gösterdi.',
    'rohan_history_5': 'Rohan\'ın en önemli özelliklerinden biri, geniş çayırları ve at sürüleridir. Rohanlılar, doğayla uyumlu bir yaşam sürer ve kahramanlık geleneğine büyük değer verir.',
    'rohan_history_6': 'Günümüzde Rohan, hala Eorl\'un soyundan gelen krallar tarafından yönetilmektedir. Atlı kültürü ve savaşçı ruhu, Rohan\'ı Orta Dünya\'nın en güçlü krallıklarından biri yapar.',
    // Gondor sayfası
    'gondor_page_title': 'Gondor',
    'gondor_quote': 'Gondor\'un beyaz kuleleri, insanlığın son umududur',
    'gondor_quote_author': 'Denethor',
    'gondor_description': 'Gondor, Orta Dünya\'nın güneyinde yer alan, insanların en güçlü krallığıdır. Minas Tirith\'in beyaz kuleleri, Númenor\'dan gelen soylu kanın ve insanlığın son umudunun simgesidir.',
    'gondor_cities': 'Gondor\'un Şehirleri',
    'gondor_culture': 'Gondor Kültürü',
    'gondor_history': 'Gondor\'un Tarihi',
    // Gondor şehirleri
    'minas_tirith_name': 'Minas Tirith',
    'minas_tirith_desc': 'Gondor\'un başkenti, Yedi Katlı Şehir. Beyaz kuleleriyle ünlü görkemli şehir.',
    'minas_morgul_name': 'Minas Morgul',
    'minas_morgul_desc': 'Eski Minas Ithil, şimdi Nazgûl\'lerin kontrolünde. Karanlık ve tehlikeli.',
    'osgiliath_name': 'Osgiliath',
    'osgiliath_desc': 'Eski başkent, Anduin nehri üzerinde kurulu. Şimdi harabe halinde.',
    'pelargir_name': 'Pelargir',
    'pelargir_desc': 'Gondor\'un liman şehri. Anduin\'in ağzında yer alır.',
    'dol_amroth_name': 'Dol Amroth',
    'dol_amroth_desc': 'Swan Knights\'in evi. Belfalas Körfezi\'nde yer alır.',
    'cair_andros_name': 'Cair Andros',
    'cair_andros_desc': 'Anduin nehri üzerindeki stratejik ada kalesi.',
    // Gondor kültürü
    'human_kingdom_title': 'İnsan Krallığı',
    'human_kingdom_desc': 'Gondor, Númenor\'dan gelen insanların kurduğu en güçlü krallıktır.',
    'white_tree_title': 'Beyaz Ağaç',
    'white_tree_desc': 'Gondor\'un sembolü, Nimloth\'un soyundan gelen kutsal ağaç.',
    'steward_system_title': 'Steward Sistemi',
    'steward_system_desc': 'Kral olmadığında, Steward\'lar krallığı yönetir.',
    'strong_army_title': 'Güçlü Ordu',
    'strong_army_desc': 'Gondor\'un ordusu, Orta Dünya\'nın en disiplinli askeri gücüdür.',
    // Gondor tarihi
    'gondor_history_1': 'Gondor, İkinci Çağ\'ın sonlarında, Númenor\'dan gelen Elendil ve oğulları tarafından kuruldu. İlk başkent Osgiliath\'tı, ancak zamanla Minas Tirith önem kazandı.',
    'gondor_history_2': 'Gondor, Númenor\'un soylu kanını taşıyan insanlar tarafından yönetilir. Krallar, Isildur\'un soyundan gelir ve Aragorn, Gondor\'un son kralı olarak tahta çıkar.',
    'gondor_history_3': 'Gondor\'un en önemli özelliklerinden biri, Beyaz Ağaç\'tır. Bu ağaç, Númenor\'dan getirilen Nimloth\'un soyundan gelir ve krallığın sağlığının simgesidir.',
    'gondor_history_4': 'Gondor, Yüzük Savaşı sırasında Sauron\'un ordularına karşı büyük bir direniş gösterdi. Minas Tirith kuşatması, Orta Dünya\'nın kaderini belirleyen en önemli savaşlardan biriydi.',
    'gondor_history_5': 'Gondor\'un ordusu, disiplinli ve güçlü savaşçılardan oluşur. Swan Knights, Dol Amroth\'tan gelen elit süvari birliğidir ve krallığın en güçlü askeri gücüdür.',
    'gondor_history_6': 'Günümüzde Gondor, Aragorn\'un yönetimi altında yeniden güçlenmiştir. Minas Tirith\'in beyaz kuleleri, insanlığın umudunun ve gücünün simgesi olarak yükselmeye devam eder.',
    // Mordor sayfası
    'mordor_page_title': 'Mordor',
    'mordor_quote': 'Tek Yüzük hepsini yönetir, Tek Yüzük hepsini bulur, Tek Yüzük hepsini bir araya getirir ve karanlıkta bağlar',
    'mordor_quote_author': 'Sauron',
    'mordor_description': 'Mordor, Orta Dünya\'nın doğusunda yer alan, Sauron\'un karanlık krallığıdır. Barad-dûr\'un karanlık kuleleri, Mount Doom\'un alevleri ve sayısız ork ordusuyla tanınır.',
    'mordor_locations': 'Mordor\'un Yerleri',
    'mordor_forces': 'Mordor\'un Güçleri',
    'mordor_history': 'Mordor\'un Tarihi',
    // Mordor yerleri
    'barad_dur_name': 'Barad-dûr',
    'barad_dur_desc': 'Sauron\'un karanlık kulesi. Mordor\'un kalbi ve karanlık gücün merkezi.',
    'mount_doom_name': 'Mount Doom',
    'mount_doom_desc': 'Orodruin, Tek Yüzük\'ün dövüldüğü ve yok edilebileceği tek yer.',
    'minas_morgul_mordor_name': 'Minas Morgul',
    'minas_morgul_mordor_desc': 'Eski Minas Ithil, şimdi Nazgûl\'lerin kontrolünde. Karanlık ve tehlikeli.',
    'cirith_ungol_name': 'Cirith Ungol',
    'cirith_ungol_desc': 'Örümcek Geçidi, Shelob\'un yaşadığı tehlikeli geçit.',
    'udun_name': 'Udûn',
    'udun_desc': 'Mordor\'un kuzey vadisi, Sauron\'un ordularının toplandığı yer.',
    'gorgoroth_name': 'Gorgoroth',
    'gorgoroth_desc': 'Mordor\'un merkezi ovası, karanlık ve çorak topraklar.',
    // Mordor güçleri
    'orcs_title': 'Orklar',
    'orcs_desc': 'Sauron\'un ana ordusu. Karanlık ve vahşi savaşçılar.',
    'nazgul_title': 'Nazgûl',
    'nazgul_desc': 'Dokuz Yüzük Taşıyıcısı, Sauron\'un en güçlü hizmetkarları.',
    'trolls_title': 'Trolls',
    'trolls_desc': 'Devasa ve güçlü yaratıklar, Sauron\'un savaş makinesinin parçası.',
    'fellbeasts_title': 'Fellbeasts',
    'fellbeasts_desc': 'Nazgûl\'lerin bineği olan kanatlı yaratıklar.',
    // Mordor tarihi
    'mordor_history_1': 'Mordor, İkinci Çağ\'da Sauron tarafından kuruldu. Bu karanlık krallık, Sauron\'un gücünün merkezi haline geldi ve Orta Dünya\'nın en tehlikeli bölgesi oldu.',
    'mordor_history_2': 'Mordor\'un kalbi Barad-dûr\'dur, Sauron\'un karanlık kulesi. Bu kule, Sauron\'un gücünün simgesidir ve Tek Yüzük\'ün etkisiyle inşa edilmiştir.',
    'mordor_history_3': 'Mount Doom (Orodruin), Mordor\'un en önemli yerlerinden biridir. Bu yanardağ, Tek Yüzük\'ün dövüldüğü ve yok edilebileceği tek yerdir. Sauron\'un gücü buradan yayılır.',
    'mordor_history_4': 'Mordor, Yüzük Savaşı sırasında Sauron\'un ordularının merkezi oldu. Sayısız ork, troll ve diğer karanlık yaratıklar buradan yola çıkarak Orta Dünya\'yı tehdit etti.',
    'mordor_history_5': 'Mordor\'un en güçlü varlıkları Nazgûl\'lerdir. Dokuz Yüzük Taşıyıcısı, Sauron\'un en güçlü hizmetkarlarıdır ve Fellbeast\'ler üzerinde uçarak korku saçarlar.',
    'mordor_history_6': 'Günümüzde Mordor, Sauron\'un yenilgisinden sonra büyük ölçüde boşaltılmıştır. Ancak karanlık güçler hala bu topraklarda gizlenmektedir ve tehlikeli yaratıklar burada yaşamaya devam eder.',
    // Mount Doom sayfası
    'mount_doom_page_title': 'MOUNT DOOM',
    'mount_doom_quote': 'Kıyamet Dağı - Yüzük\'ün Yaratıldığı ve Yok Edildiği Yer',
    'mount_doom_quote_author': 'Ateş Çukuru',
    'mount_doom_description': 'Mount Doom, Mordor\'un kalbinde yükselen devasa bir yanardağıdır. Bu dağ, Sauron\'un gücünün merkezi ve Yüzük\'ün yaratıldığı yerdir.',
    'mount_doom_history_importance': 'Tarih ve Önem',
    'physical_features': 'Fiziksel Özellikler',
    'important_events': 'Önemli Olaylar',
    'cultural_importance': 'Kültürel Önem',
    // Mount Doom tarih ve önem
    'mount_doom_history_1': 'Mount Doom, Mordor\'un kalbinde yükselen devasa bir yanardağıdır. Bu dağ, Sauron\'un gücünün merkezi ve Yüzük\'ün yaratıldığı yerdir. Dağın zirvesindeki Ateş Çukuru, Yüzük\'ün yok edilebileceği tek yerdir.',
    'mount_doom_history_2': 'İkinci Çağ\'da Sauron, bu dağı kendi gücünün merkezi haline getirdi ve Yüzük\'ü burada yarattı. Dağın sürekli lav püskürmesi ve karanlık atmosferi, Mordor\'un ürkütücü doğasını simgeler.',
    'mount_doom_history_3': 'Yüzük Savaşı sırasında, Frodo ve Sam\'in son görevi bu dağa ulaşmak ve Yüzük\'ü Ateş Çukuru\'na atmaktı. Bu yolculuk, Orta Dünya\'nın kaderini belirleyecek en tehlikeli görevdi.',
    // Mount Doom fiziksel özellikler
    'mountain_structure_title': 'Dağın Yapısı',
    'mountain_structure_desc': 'Konik şekilli dağ, sürekli lav püskürür ve çevresini karanlık dumanlarla sarar. Dağın zirvesindeki krater, Yüzük\'ün yok edilebileceği Ateş Çukuru\'nu barındırır.',
    'atmosphere_title': 'Atmosfer',
    'atmosphere_desc': 'Dağın çevresi sürekli karanlık bulutlarla kaplıdır. Lav ışığı ve dumanlar, bölgeye ürkütücü bir hava verir. Hava sürekli sıcak ve zehirli gazlarla doludur.',
    'fire_pit_title': 'Ateş Çukuru',
    'fire_pit_desc': 'Dağın zirvesindeki krater, Yüzük\'ün yaratıldığı ve yok edilebileceği tek yerdir. Bu çukur, Sauron\'un gücünün kaynağıdır ve sürekli lav püskürür.',
    // Mount Doom önemli olaylar
    'ring_creation_title': 'Yüzük\'ün Yaratılması',
    'ring_creation_desc': 'İkinci Çağ\'da Sauron, Mount Doom\'da Tek Yüzük\'ü yarattı. Bu yüzük, diğer güç yüzüklerini kontrol etmek için tasarlanmıştı.',
    'frodo_journey_title': 'Frodo\'nun Yolculuğu',
    'frodo_journey_desc': 'Frodo ve Sam, Yüzük\'ü yok etmek için Mount Doom\'a ulaştılar. Bu yolculuk, Orta Dünya\'nın kaderini belirleyecek en tehlikeli görevdi.',
    'ring_destruction_title': 'Yüzük\'ün Yok Edilmesi',
    'ring_destruction_desc': 'Gollum\'un müdahalesiyle Yüzük Ateş Çukuru\'na düştü ve yok oldu. Bu olay, Sauron\'un gücünü tamamen yok etti ve Üçüncü Çağ\'ı sonlandırdı.',
    // Mount Doom kültürel önem
    'symbolic_meaning_title': 'Sembolik Anlam',
    'symbolic_meaning_desc_1': 'Mount Doom, kötülüğün ve yıkımın sembolüdür. Dağın sürekli lav püskürmesi, Sauron\'un sürekli artan gücünü temsil eder.',
    'symbolic_meaning_desc_2': 'Aynı zamanda, umudun ve fedakarlığın da sembolüdür. Frodo\'nun bu dağa çıkması, iyiliğin kötülüğe karşı verdiği mücadelenin en büyük örneğidir.',
    'literary_importance_title': 'Edebi Önem',
    'literary_importance_desc_1': 'J.R.R. Tolkien\'in eserlerinde Mount Doom, karanlık güçlerin merkezi olarak tasvir edilmiştir. Dağ, Orta Dünya\'nın en tehlikeli ve korkunç yeridir.',
    'literary_importance_desc_2': 'Dağın fiziksel özellikleri ve atmosferi, okuyucuya kötülüğün doğasını hissettirmek için tasarlanmıştır.',
    // Helm's Deep sayfası
    'helms_deep_page_title': 'HELM\'S DEEP',
    'helms_deep_quote': 'Miğfer Dibi - Rohan\'ın Geçilmez Kalesi',
    'helms_deep_quote_author': 'Hornburg',
    'helms_deep_description': 'Helm\'s Deep, Rohan\'ın en güçlü kalesidir. White Mountains\'ın eteklerinde yer alan bu geçilmez kale, Rohan\'ın son savunma hattıdır ve tarihte birçok büyük savaşa tanıklık etmiştir.',
    'history_and_importance_helms': 'Tarih ve Önem',
    'great_battle': 'Büyük Savaş',
    'fortress_features': 'Kale Özellikleri',
    'battle_heroes': 'Savaşın Kahramanları',
    // Helm's Deep tarih ve önem
    'helms_deep_history_1': 'Helm\'s Deep, Rohan\'ın White Mountains\'da yer alan en güçlü kalesidir. Bu kale, Rohan\'ın doğu sınırını korur ve düşman saldırılarına karşı son savunma hattıdır.',
    'helms_deep_history_2': 'Kale, Rohan\'ın eski kralı Helm Hammerhand tarafından inşa edilmiştir. Kalenin adı da buradan gelir. White Mountains\'ın doğal kayalıkları üzerine kurulan kale, geçilmez bir yapıya sahiptir.',
    'helms_deep_history_3': 'Yüzük Savaşı sırasında, Helm\'s Deep Rohan\'ın son umudu haline gelmiştir. Saruman\'ın ordularına karşı verilen bu savaş, Orta Dünya\'nın kaderini belirleyecek en önemli savaşlardan biri olmuştur.',
    // Helm's Deep savaş
    'battle_of_helms_deep': 'Miğfer Dibi Savaşı',
    'battle_start_title': 'Savaşın Başlangıcı',
    'battle_start_desc': 'Saruman\'ın 10.000 orkluk ordusu, Rohan\'ı işgal etmek için Helm\'s Deep\'e saldırdı. Rohan\'ın kralı Théoden, halkını bu kaleye sığınmaya zorladı.',
    'defense_title': 'Savunma',
    'defense_desc': 'Aragorn, Legolas ve Gimli\'nin de katıldığı savunma, gece boyunca sürdü. Orklar kalenin duvarlarını aşmaya çalıştı, ancak Rohan\'ın savaşçıları kahramanca direndi.',
    'gandalf_arrival_title': 'Gandalf\'ın Gelişi',
    'gandalf_arrival_desc': 'Şafak sökerken Gandalf, Éomer ile birlikte geldi. Güneş ışığında orklar dağıldı ve Rohan zafer kazandı. Bu savaş, Saruman\'ın gücünün kırılmasında önemli rol oynadı.',
    // Helm's Deep kale özellikleri
    'hornburg_title': 'Hornburg',
    'hornburg_desc': 'Kalenin ana kulesi olan Hornburg, White Mountains\'ın en yüksek noktasında yer alır. Bu kule, düşman hareketlerini gözlemlemek için mükemmel bir konumdadır.',
    'deeping_wall_title': 'Deeping Wall',
    'deeping_wall_desc': 'Kalenin ana savunma duvarı olan Deeping Wall, 20 metre yüksekliğinde ve geçilmez bir yapıya sahiptir. Duvarın üzerinde okçular için özel mevziler bulunur.',
    'deeping_coomb_title': 'Deeping Coomb',
    'deeping_coomb_desc': 'Kalenin önündeki vadi olan Deeping Coomb, düşman ordularını sınırlar ve savunma için doğal bir engel oluşturur. Bu vadi, savaş sırasında orkların toplandığı yerdir.',
    // Helm's Deep kahramanlar
    'aragorn_hero_title': 'Aragorn',
    'aragorn_hero_desc_1': 'Savaş sırasında Rohan\'ın savunmasına öncülük etti. Cesareti ve liderliği ile orklara karşı mücadelede büyük rol oynadı.',
    'aragorn_hero_quote': 'Gece boyunca savaştık, ama şafak söktüğünde zafer bizimdi.',
    'legolas_gimli_title': 'Legolas ve Gimli',
    'legolas_gimli_desc_1': 'Elf ve cüce dostluğunun en güzel örneği. Savaş sırasında birlikte savaştılar ve birbirlerini korudular.',
    'legolas_gimli_desc_2': 'Gimli\'nin öldürdüğü ork sayısı ile Legolas\'ın ok attığı hedef sayısı arasında dostça bir yarış vardı.',
    'map_title': 'Orta Dünya Haritası',
    'map_subtitle': 'Büyülü toprakları keşfedin',
    'shop_title': 'Ürünlerimiz',
    'shop_subtitle': 'Orta Dünya\'dan özel ürünler',
    'view_all': 'Tümünü Gör',
    'add_to_cart': 'Sepete Ekle',
    'price': 'Fiyat',
    'category': 'Kategori',
    // Shop kategorileri
    'rings': 'Yüzükler',
    'swords': 'Kılıçlar',
    'cloaks': 'Pelerinler',
    'maps': 'Haritalar',
    'figures': 'Figürler',
    'elf_jewelry': 'Elf Takıları',
    'books': 'Orta Dünya Kitapları',
    'hobbit_items': 'Hobbit Eşyaları',
    'elf_bows': 'Elf Yayları',
    'dwarf_axes': 'Cüce Baltaları',
    'nazgul_masks': 'Nazgûl Maskeleri',
    'orc_armors': 'Ork Zırhları',
    'wizard_staffs': 'Büyücü Asaları',
    'gondor_helmets': 'Gondor Miğferleri',
    'rohan_horses': 'Rohan At Figürleri',
    'posters': 'Orta Dünya Posterleri',
    'cards': 'Koleksiyon Kartları',
    'collection_figures': 'Koleksiyon Figürleri',
    'home_office': 'Ev & Ofis',
    'accessories': 'Aksesuar & Takı',
    'clothes': 'Kıyafet',
    'games_puzzles': 'Oyun & Puzzle',
    'kitchen': 'Mutfak',
    'coins_replicas': 'Koleksiyon Paraları & Replikalar',
    'plush_toys': 'Peluş & Oyuncak',
    // Shop butonları
    'buy_now': 'Satın Al',
    'checkout': 'Ödeme',
    'cart_summary': 'Sepetiniz',
    'no_cart_items': 'Sepetinizde ürün yok.',
    'total': 'Toplam',
    'product': 'Ürün',
    'quantity': 'Miktar',
    'action': 'İşlem',
    'remove_from_cart': 'Sepetten Çıkar',
    'continue_shopping': 'Alışverişe Devam Et',
    'card_info': 'Kart Bilgileri',
    'card_name_placeholder': 'Kart Üzerindeki İsim',
    'card_number_placeholder': 'Kart Numarası',
    'expiry_placeholder': 'AA/YY',
    'cvc_placeholder': 'CVC',
    'email_placeholder': 'E-posta',
    'address_placeholder': 'Teslimat Adresi',
    'complete_payment': 'Ödemeyi Tamamla',
    'payment_success': 'Ödeme Başarılı!',
    'payment_success_desc': 'Siparişin alındı, Orta Dünya\'ya hoş geldin! 🧙‍♂️',
    'go_home': 'Anasayfaya Dön',
    // Profil menüsü
    'orders_title': 'Siparişlerim',
    'order_number': 'Sipariş',
    'order_date': 'Tarih',
    'order_status_delivered': 'Teslim Edildi',
    'order_status_shipping': 'Kargoda',
    'order_status_preparing': 'Hazırlanıyor',
    'order_status_cancelled': 'İptal Edildi',
    'order_status_pending': 'Beklemede',
    'delivery_address': 'Teslimat Adresi',
    'total_amount': 'Toplam Tutar',
    'ordered_products': 'Sipariş Edilen Ürünler',
    'order_loading': 'Yükleniyor...',
    'order_none': 'Henüz bir siparişiniz yok.',
    'order_first_cta': 'İlk siparişinizi vermek için',
    'order_first_link': 'ürünlerimizi',
    'order_first_end': 'inceleyin.',
    'order_product_none': 'Ürün bilgisi bulunamadı.',
    'currency_try': '₺',
    'currency_usd': '$',
    'requests_title': 'Soru ve Taleplerim',
    'requests_help_title': 'Size nasıl yardımcı olabiliriz?',
    'requests_help_sub': 'Sorularınızı ve taleplerinizi buradan iletebilirsiniz.',
    'select_category': 'Kategori seçiniz',
    'category_product': 'Ürün Bilgisi',
    'category_order': 'Sipariş Durumu',
    'category_return': 'İade/Değişim',
    'category_technical': 'Teknik Destek',
    'category_suggestion': 'Öneri/Şikayet',
    'category_other': 'Diğer',
    'subject_placeholder': 'Mesajınızın konusu',
    'priority_low': 'Düşük',
    'priority_normal': 'Normal',
    'priority_high': 'Yüksek',
    'priority_urgent': 'Acil',
    'message_placeholder': 'Detaylı mesajınızı buraya yazın...',
    'send_message': 'Mesajı Gönder',
    'sending': 'Gönderiliyor...',
    'contact_info': 'İletişim Bilgileri',
    'work_hours': 'Çalışma Saatleri',
    'past_requests': 'Geçmiş Talepleriniz',
    'no_requests': 'Henüz bir soru veya talebiniz yok.',
    'topic': 'Konu',
    'your_message': 'Mesajınız',
    'reply': 'Yanıt',
    'pending': 'Beklemede',
    'answered': 'Yanıtlandı',
    'required_fields': 'Lütfen tüm zorunlu alanları doldurun.',
    'user_not_found': 'Kullanıcı bulunamadı.',
    'db_error': 'Firestore bağlantısı kurulamadı.',
    'send_success': 'Mesajınız başarıyla gönderildi! En kısa sürede size dönüş yapacağız.',
    'send_error': 'Bir hata oluştu. Lütfen tekrar deneyin.',
    // --- OFFERS PAGE ---
    'loading': 'Yükleniyor...',
    'no_offers': 'Şu anda sana özel bir fırsat yok.',
    'follow_for_offers': 'Yeni fırsatlar için bizi takip etmeye devam edin!',
    'coupon_code': 'Kupon Kodu',
    'expiry_date': 'Son Kullanım Tarihi',
    'min_amount': 'Minimum Tutar',
    'start_shopping': 'Alışverişe Başla',
    'copy_code': 'Kodu Kopyala',
    'offers_email_tip': 'Fırsatları kaçırmamak için e-posta bildirimlerini açmayı unutmayın!',
    'discount': 'İndirim',
    'shipping': 'Kargo',
    'gift': 'Hediye',
    'offer': 'Fırsat',
    // --- PROFILE PAGE ---
    'profile_tab_info': 'Üyelik Bilgilerim',
    'profile_tab_password': 'Şifre Değişikliği',
    'profile_tab_prefs': 'İletişim Tercihlerim',
    'profile_tab_addresses': 'Adreslerim',
    'profile_tab_update': 'Bilgilerimi Güncelle',
    'first_name': 'Ad',
    'last_name': 'Soyad',
    'birth_date': 'Doğum Tarihi',
    'gender_select': 'Cinsiyet (seçiniz)',
    'gender_male': 'Erkek',
    'gender_female': 'Kadın',
    'gender_other': 'Diğer',
    'phone_number': 'Telefon Numarası',
    'email_address': 'Mail Adresi',
    'profile_info_note': 'Bilgiler sadece ilk kayıt sırasında doldurulabilir. Güncellemek için "Bilgilerimi Güncelle" sekmesini kullan.',
    'address_title': 'Adres Başlığı',
    'country_turkey': 'Türkiye',
    'city': 'Şehir',
    'district': 'İlçe',
    'address_detail': 'Açık Adres',
    'add': 'Ekle',
    'adding': 'Ekleniyor...',
    'saved_addresses': 'Kayıtlı Adresler:',
    'no_addresses': 'Henüz adres eklemediniz.',
    'delete': 'Sil',
    'password': 'Şifre',
    'current_password': 'Mevcut Şifre',
    'new_password': 'Yeni Şifre',
    'checking': 'Kontrol Ediliyor...',
    'continue': 'Devam Et',
    'update': 'Güncelle',
    'updating': 'Güncelleniyor...',
    'verifying': 'Doğrulanıyor...',
    'save': 'Kaydet',
    'saving': 'Kaydediliyor...',
    'sms_channel': 'Anlık/Kısa Mesaj Kanalları',
    'email_channel': 'E-Posta',
    'phone_channel': 'Telefon Araması',
  },
  en: {
    // Navbar
    'home': 'Home',
    'characters': 'Characters',
    'stories': 'Stories',
    'gallery': 'Gallery',
    'map': 'Map',
    'shop': 'Shop',
    'login': 'Login',
    'register': 'Register',
    'profile': 'Profile',
    'cart': 'Cart',
    'orders': 'My Orders',
    'requests': 'Questions & Requests',
    'offers': 'Special Offers',
    'profile_info': 'User Info',
    'reviews': 'My Reviews',
    'favorites': 'Favorites',
    'no_favorites': 'You have not favorited any products yet.',
    'my_reviews': 'My Reviews',
    'no_reviews': 'You have not written any reviews yet.',
    'all_lists': 'ALL MY LISTS',
    'favorite_lists': 'Favorite Lists',
    'shopping_lists': 'Shopping Lists',
    'compare_list': 'Compare List',
    'reviewed_products': 'Reviewed Products',
    'shared_lists': 'Shared Lists',
    'new_list': '+ New List',
    'create': 'Create',
    'list_name_placeholder': 'Enter list name...',
    'lists': 'All Lists',
    'logout': 'Logout',
    'hello': 'Hello',
    'menu': 'Toggle Menu',
    
    // Dil seçenekleri
    'language': 'Language',
    'turkish': 'Turkish',
    'english': 'English',

    // Ana Sayfa
    'welcome_title': 'Welcome to Middle-earth',
    'welcome_subtitle': 'Step into the magical world of The Lord of the Rings',
    'explore_button': 'Explore the Ring',
    'explore_characters': 'Explore Characters',
    'explore_stories': 'Explore Stories',
    'explore_gallery': 'Explore Gallery',
    'explore_map': 'Explore the Map',
    'explore_shop': 'Explore Products',
    'learn_more': 'Learn More',
    'characters_title': 'Legendary Characters',
    'characters_subtitle': 'Middle-earth\'s most unforgettable heroes and villains',
    'good_characters': 'Good Characters',
    'evil_characters': 'Evil Characters',
    'stories_title': 'Epic Stories',
    'stories_subtitle': 'Middle-earth\'s greatest adventures',
    'gallery_title': 'Gallery',
    'gallery_subtitle': 'Middle-earth\'s most beautiful images',
    // Gallery page
    'gallery_page_title': 'Gallery',
    'fellowship': 'Fellowship of the Ring',
    'shire': 'Shire',
    'rivendell': 'Rivendell',
    'rohan': 'Rohan',
    'gondor': 'Gondor',
    'mordor': 'Mordor',
    'mount_doom': 'Mount Doom',
    'helms_deep': 'Helm\'s Deep',
    'galadriel': 'Galadriel',
    // Fellowship page
    'fellowship_page_title': 'Fellowship of the Ring',
    'fellowship_quote': 'The Fellowship of the Ring shall be Nine; and Nine Walkers shall be set against the Nine Riders that are evil',
    'fellowship_quote_author': 'Elrond',
    'fellowship_description': 'The Fellowship of the Ring, also known as the Company of the Ring, consisted of nine members of the Free Peoples during the War of the Ring. Their purpose was to take the One Ring to Mordor, the only place where it could be destroyed.',
    'view_members': 'View Members',
    'members_title': 'Members',
    'age_label': 'Age',
    'history_title': 'History',
    'return_home': 'Return to Home',
    // Fellowship members
    'gandalf_name': 'Gandalf',
    'gandalf_desc': 'One of the Wizards sent to Middle-earth by the Valar. He was the leader of the Fellowship.',
    'aragorn_name': 'Aragorn',
    'aragorn_desc': 'Son of Arathorn. Chief of the Dúnedain and the last heir of the thrones of Gondor and Arnor. He led the Fellowship after Gandalf\'s loss.',
    'boromir_name': 'Boromir',
    'boromir_desc': 'Son of Denethor. Captain/general of Gondor and the next in line to be Steward of Gondor.',
    'legolas_name': 'Legolas',
    'legolas_desc': 'Son of Thranduil of Mirkwood. Ambassador of the Mirkwood Elves.',
    'gimli_name': 'Gimli',
    'gimli_desc': 'Son of Glóin. A dwarf from the Lonely Mountain.',
    'frodo_name': 'Frodo Baggins',
    'frodo_desc': 'A hobbit from the Shire. Chosen to be the Ring-bearer.',
    'sam_name': 'Samwise Gamgee',
    'sam_desc': 'A hobbit, Frodo\'s gardener, servant, and close friend.',
    'merry_name': 'Meriadoc "Merry" Brandybuck',
    'merry_desc': 'A hobbit, Frodo\'s cousin, Pippin\'s best friend.',
    'pippin_name': 'Peregrin "Pippin" Took',
    'pippin_desc': 'A hobbit, Frodo\'s cousin, the youngest member of the Fellowship.',
    // Fellowship history translations
    'fellowship_history_1': 'The Fellowship of the Ring was formed in Rivendell with the purpose of destroying the One Ring, and the only way to do this was to cast it into the Cracks of Doom. It was decided that there should be nine walkers against Sauron\'s nine riders, with Frodo as the Ring-bearer and Gandalf as the leader.',
    'fellowship_history_2': 'Although the purpose was determined by Elrond\'s Council, how, in what manner, and by what route this could be accomplished was not decided; such details were left to the Fellowship\'s discretion. As a result, the Fellowship started without a detailed plan. One option was to go directly to Mount Doom, the other was to seek help from Boromir\'s father Denethor II.',
    'fellowship_history_3': 'How to reach the East was a problem. After passing south from Rivendell, they encountered crebain upon their arrival in Hollin. Fearing that they were being used as spies by Saruman, the Fellowship spent the whole day hiding without a campfire.',
    'fellowship_history_4': 'When they had to cross the Misty Mountains; Boromir suggested the Gap of Rohan, Gandalf insisted on passing through Moria, but Aragorn thought the Redhorn Pass would be safer. However, after trying in vain to pass the storm, they followed Gandalf\'s option.',
    'fellowship_history_5': 'After fighting with wolves and the Watcher in the Water, they managed to open the Doors of Durin and enter Moria. There they found the Orcs who had captured Balin\'s Colony years ago. They also saw Durin\'s Bane, which had devastated Moria in the first place.',
    'fellowship_history_6': 'Gandalf destroyed the Bridge of Khazad-dûm to buy them time, and while both Maiar fell into the abyss, the others reached the light; Aragorn was brought to the head of the group, and their next stop was to meet with Lothlórien\'s elf lords Galadriel and Celeborn.',
    'fellowship_history_7': 'They stayed there for four weeks, resting and pondering their plans and routes. When they left, the elves gave them various gifts and a boat to sail to the Anduin.',
    'fellowship_history_8': 'Meanwhile, Saruman, who served Sauron, sent a group of Uruk-hai to capture the halfling carrying the Ring and bring him to Isengard. Frodo began to notice not only that someone was following them, but also that the Ring had a malevolent effect on some party members, especially Boromir.',
    'fellowship_history_9': 'It was he who tried to take the ring from him after passing through the Argonath. At this time, Frodo put on the ring to escape from him, but Sam followed him. While the rest of the Fellowship tried to find the Ring-bearer, they were attacked by orcs. Not seeing another halfling, the Orcs managed to capture Merry and Pippin and killed Boromir, who tried to protect them.',
    'fellowship_history_10': 'And thus, the Fellowship was broken, but not yet scattered. Sam followed Frodo, who decided to go to Mordor alone, down from Emyn Muil. Aragorn with Gimli and Legolas ("The Three Hunters") decided to follow the Orcs to Rohan and rescue Pippin and Merry. Unbeknownst to all, Gandalf was resurrected and visited Lothlórien after them.',
    'fellowship_history_11': 'After many adventures, the remaining eight Fellowship members came together again after Sauron\'s downfall. When King Théoden\'s funeral procession set out from Minas Tirith, the eight companions traveled together until they met Treebeard at Orthanc. There Gimli and Legolas set out to visit the deep regions of Fangorn Forest on their way home, and Aragorn declared that the Fellowship of the Ring had finally ended.',
    // Shire page
    'shire_page_title': 'Shire',
    'shire_quote': 'In the Shire everything is green and beautiful, and hobbits live in peace',
    'shire_quote_author': 'Bilbo Baggins',
    'shire_description': 'The Shire is located in the northwest of Middle-earth and is the homeland of the hobbits. This region, famous for its green hills, lush meadows, and peaceful hobbit holes, is a symbol of peace and prosperity.',
    'explore_locations': 'Explore Places',
    'explore_cities': 'Explore Cities',
    'learn_culture': 'Learn Culture',
    'learn_forces': 'Learn Forces',
    'important_locations': 'Important Places',
    'hobbit_culture': 'Hobbit Culture',
    'shire_history': 'History of the Shire',
    // Shire locations
    'hobbiton_name': 'Hobbiton',
    'hobbiton_desc': 'The heart of the Shire, the largest settlement of hobbits. Famous for its green hills and hobbit holes.',
    'bag_end_name': 'Bag End',
    'bag_end_desc': 'The home of the Baggins family, where Bilbo and Frodo lived. The most beautiful hobbit hole in the Shire.',
    'green_dragon_name': 'Green Dragon Inn',
    'green_dragon_desc': 'The famous inn where hobbits gather. Famous for its beer and food.',
    'brandy_hall_name': 'Brandy Hall',
    'brandy_hall_desc': 'The large home of the Brandybuck family. Located in Buckland.',
    'tookland_name': 'Tookland',
    'tookland_desc': 'The lands of the Took family. The westernmost region of the Shire.',
    'michel_delving_name': 'Michel Delving',
    'michel_delving_desc': 'The capital of the Shire. The Shire-moot meets in the Great Smials.',
    // Hobbit culture
    'hobbit_lifestyle_title': 'Hobbit Lifestyle',
    'hobbit_lifestyle_desc': 'Hobbits are a calm, peaceful, and land-bound people. They love eating, drinking beer, and gardening.',
    'hobbit_holes_title': 'Hobbit Holes',
    'hobbit_holes_desc': 'Hobbits live in round-doored, earth-embedded houses. These homes are both warm and secure.',
    'shire_calendar_title': 'Shire Calendar',
    'shire_calendar_desc': 'Hobbits use their own calendar. New Year is celebrated on March 25th, and Mid-year on June 22nd.',
    'hobbit_cuisine_title': 'Hobbit Cuisine',
    'hobbit_cuisine_desc': 'They eat 6 meals a day: Breakfast, second breakfast, elevenses, lunch, tea, and dinner.',
    // Shire history
    'shire_history_1': 'The Shire was founded in the year 1601 of the Third Age, when hobbits settled in Eriador. The first settlers were two brothers named Marcho and Blanco from Bree. King Argeleb II of Gondor gave the Shire to the hobbits and granted them full autonomy.',
    'shire_history_2': 'The Shire is divided into four regions: North, South, East, and West Farthing. Each region has its own characteristics and hobbit families. The most important families are Baggins, Took, Brandybuck, and Gamgee.',
    'shire_history_3': 'Hobbits live peacefully in the Shire and have very little contact with the outside world. They have their own governance system: Thain (military leader), Mayor (civil administrator), and Shirriffs (police force).',
    'shire_history_4': 'Among the Shire\'s most famous residents are Bilbo Baggins (the main character at the beginning of The Lord of the Rings) and his nephew Frodo Baggins (the Ring-bearer). These two hobbits embarked on adventures that changed the fate of Middle-earth.',
    'shire_history_5': 'The Shire was occupied by Saruman during the War of the Ring and suffered great damage. However, after the war, the Shire was rebuilt by Aragorn\'s order, and the hobbits returned to their peaceful lives.',
    'shire_history_6': 'Today, the Shire is the most peaceful and prosperous region in Middle-earth. Hobbits continue to live peacefully in their round-doored homes in the green hills.',
    // Rivendell page
    'rivendell_page_title': 'Rivendell',
    'rivendell_quote': 'In Rivendell peace and wisdom are found, here time stands still',
    'rivendell_quote_author': 'Elrond',
    'rivendell_description': 'Rivendell (Imladris), one of the most beautiful and peaceful places in Middle-earth. This hidden valley, ruled by the Elf Lord Elrond, is a sanctuary where the wounded heal, the wise gather, and travelers rest.',
    'explore_features': 'Explore Features',
    'elf_culture': 'Elf Culture',
    'rivendell_features': 'Features of Rivendell',
    'rivendell_history': 'History of Rivendell',
    // Rivendell features
    'elronds_house_name': 'Elrond\'s House',
    'elronds_house_desc': 'The heart of Rivendell, the magnificent house where Elrond lives and hosts his guests.',
    'waterfalls_name': 'Waterfalls',
    'waterfalls_desc': 'Magnificent waterfalls flowing down from the mountains add a magical atmosphere to Rivendell.',
    'bridges_name': 'Bridges',
    'bridges_desc': 'Elegant arched stone bridges connect different parts of the city.',
    'library_name': 'Library',
    'library_desc': 'The center of Elf wisdom where ancient knowledge is stored.',
    'gardens_name': 'Gardens',
    'gardens_desc': 'Lush gardens filled with flowers, peaceful places.',
    'healing_rooms_name': 'Healing Rooms',
    'healing_rooms_desc': 'Special rooms where Elf healers work to heal the wounded.',
    // Elf culture
    'elf_wisdom_title': 'Elf Wisdom',
    'elf_wisdom_desc': 'Elves possess thousands of years of knowledge. Rivendell is one of the greatest centers of wisdom in Middle-earth.',
    'elf_architecture_title': 'Elf Architecture',
    'elf_architecture_desc': 'Elegant, organic lines and nature-compatible design. Rivendell\'s buildings are both beautiful and functional.',
    'elf_art_title': 'Elf Art',
    'elf_art_desc': 'Elves who have mastered music, poetry, and visual arts value beauty above all else.',
    'immortality_title': 'Immortality',
    'immortality_desc': 'Elves are immortal and perceive the passage of time differently. This gives them a unique perspective.',
    // Rivendell history
    'rivendell_history_1': 'Rivendell was founded in the late Second Age by Elrond. Elrond was part of the Last Alliance that fought against Sauron\'s forces, and after the war, he built a sanctuary in this hidden valley.',
    'rivendell_history_2': 'Rivendell became one of the most important centers of wisdom in Middle-earth over time. Ancient books are stored here, the wise gather, and the wounded are healed. Elrond\'s house hosts guests from all races.',
    'rivendell_history_3': 'One of Rivendell\'s most important features is that time flows differently here. The valley is isolated from the outside world and maintains its peaceful atmosphere. This creates an ideal environment for the healing of the wounded and the rest of travelers.',
    'rivendell_history_4': 'Rivendell played a critical role during the War of the Ring. The Fellowship of the Ring was formed here and Frodo\'s wound was healed. Elrond\'s Council made decisions that changed the fate of Middle-earth.',
    'rivendell_history_5': 'Rivendell\'s architecture is one of the most beautiful examples of Elf art. Elegant arches, graceful decorations, and nature-compatible design make this one of the most beautiful places in Middle-earth.',
    'rivendell_history_6': 'Today, Rivendell still serves as one of the most peaceful and secure places in Middle-earth under Elrond\'s rule. Here time stands still and wisdom is preserved forever.',
    // Rohan page
    'rohan_page_title': 'Rohan',
    'rohan_quote': 'In Rohan horses run free and warriors fight bravely',
    'rohan_quote_author': 'King Théoden',
    'rohan_description': 'Rohan is a powerful kingdom located in the north of Middle-earth, famous for its mounted warriors. It is known for its vast meadows, brave warriors, and free-spirited people.',
    'rohan_locations': 'Important Places',
    'rohan_culture': 'Rohan Culture',
    'rohan_history': 'History of Rohan',
    // Rohan locations
    'edoras_name': 'Edoras',
    'edoras_desc': 'The capital of Rohan, famous for Meduseld (Golden Hall). A magnificent city built on a hill.',
    'meduseld_name': 'Meduseld',
    'meduseld_desc': 'The palace of the kings of Rohan. A magnificent structure known as the Golden Hall.',
    'helms_deep_name': 'Helm\'s Deep',
    'helms_deep_desc': 'Rohan\'s strongest fortress. Also known as Hornburg.',
    'aldburg_name': 'Aldburg',
    'aldburg_desc': 'Eorl\'s old capital. Rohan\'s first settlement.',
    'westfold_name': 'Westfold',
    'westfold_desc': 'Rohan\'s western region. Famous for vast meadows and horse herds.',
    'eastfold_name': 'Eastfold',
    'eastfold_desc': 'Rohan\'s eastern region. Extends along the Anduin River.',
    // Rohan culture
    'horse_culture_title': 'Horse Culture',
    'horse_culture_desc': 'The Rohirrim have formed a strong bond with horses. They have mastered horsemanship.',
    'warrior_spirit_title': 'Warrior Spirit',
    'warrior_spirit_desc': 'The Rohirrim are brave warriors. Their cavalry units are among the strongest in Middle-earth.',
    'meadow_life_title': 'Meadow Life',
    'meadow_life_desc': 'The Rohirrim living in vast meadows lead a life in harmony with nature.',
    'heroism_tradition_title': 'Heroism Tradition',
    'heroism_tradition_desc': 'In Rohan, heroism and honor are the highest values.',
    // Rohan history
    'rohan_history_1': 'Rohan was founded in the year 2510 of the Third Age. Eorl the Young came from the north to help Gondor and received the lands of Calenardhon. These lands are now known as Rohan.',
    'rohan_history_2': 'The Rohirrim are ruled by kings descended from Eorl. Their capital is Edoras, and their most important structure is the royal palace known as Meduseld (Golden Hall).',
    'rohan_history_3': 'Rohan is famous for its mounted warriors. Their cavalry units are among the strongest military forces in Middle-earth. The Rohirrim have formed a strong bond with horses and mastered horsemanship.',
    'rohan_history_4': 'Rohan played a critical role during the War of the Ring. They showed great resistance against Saruman\'s armies in the Battle of Helm\'s Deep. Under King Théoden\'s leadership, Rohan helped Gondor and showed great heroism in the Battle of Pelennor.',
    'rohan_history_5': 'One of Rohan\'s most important features is its vast meadows and horse herds. The Rohirrim lead a life in harmony with nature and greatly value the tradition of heroism.',
    'rohan_history_6': 'Today, Rohan is still ruled by kings descended from Eorl. The horse culture and warrior spirit make Rohan one of the strongest kingdoms in Middle-earth.',
    // Gondor page
    'gondor_page_title': 'Gondor',
    'gondor_quote': 'The white towers of Gondor are the last hope of mankind',
    'gondor_quote_author': 'Denethor',
    'gondor_description': 'Gondor is the strongest kingdom of men located in the south of Middle-earth. The white towers of Minas Tirith are the symbol of noble blood from Númenor and the last hope of mankind.',
    'gondor_cities': 'Cities of Gondor',
    'gondor_culture': 'Gondor Culture',
    'gondor_history': 'History of Gondor',
    // Gondor cities
    'minas_tirith_name': 'Minas Tirith',
    'minas_tirith_desc': 'The capital of Gondor, the Seven-tiered City. A magnificent city famous for its white towers.',
    'minas_morgul_name': 'Minas Morgul',
    'minas_morgul_desc': 'Former Minas Ithil, now under the control of the Nazgûl. Dark and dangerous.',
    'osgiliath_name': 'Osgiliath',
    'osgiliath_desc': 'The old capital, built on the Anduin River. Now in ruins.',
    'pelargir_name': 'Pelargir',
    'pelargir_desc': 'Gondor\'s port city. Located at the mouth of the Anduin.',
    'dol_amroth_name': 'Dol Amroth',
    'dol_amroth_desc': 'Home of the Swan Knights. Located in the Bay of Belfalas.',
    'cair_andros_name': 'Cair Andros',
    'cair_andros_desc': 'Strategic island fortress on the Anduin River.',
    // Gondor culture
    'human_kingdom_title': 'Human Kingdom',
    'human_kingdom_desc': 'Gondor is the strongest kingdom founded by men from Númenor.',
    'white_tree_title': 'White Tree',
    'white_tree_desc': 'The symbol of Gondor, the sacred tree descended from Nimloth.',
    'steward_system_title': 'Steward System',
    'steward_system_desc': 'When there is no king, Stewards rule the kingdom.',
    'strong_army_title': 'Strong Army',
    'strong_army_desc': 'Gondor\'s army is the most disciplined military force in Middle-earth.',
    // Gondor history
    'gondor_history_1': 'Gondor was founded in the late Second Age by Elendil and his sons who came from Númenor. The first capital was Osgiliath, but over time Minas Tirith gained importance.',
    'gondor_history_2': 'Gondor is ruled by men who carry the noble blood of Númenor. Kings descend from Isildur, and Aragorn ascends to the throne as the last king of Gondor.',
    'gondor_history_3': 'One of Gondor\'s most important features is the White Tree. This tree descends from Nimloth brought from Númenor and is the symbol of the kingdom\'s health.',
    'gondor_history_4': 'Gondor showed great resistance against Sauron\'s armies during the War of the Ring. The siege of Minas Tirith was one of the most important battles that determined the fate of Middle-earth.',
    'gondor_history_5': 'Gondor\'s army consists of disciplined and powerful warriors. The Swan Knights are an elite cavalry unit from Dol Amroth and are the kingdom\'s strongest military force.',
    'gondor_history_6': 'Today, Gondor has regained strength under Aragorn\'s rule. The white towers of Minas Tirith continue to rise as a symbol of mankind\'s hope and power.',
    // Mordor page
    'mordor_page_title': 'Mordor',
    'mordor_quote': 'One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them',
    'mordor_quote_author': 'Sauron',
    'mordor_description': 'Mordor is Sauron\'s dark kingdom located in the east of Middle-earth. It is known for the dark towers of Barad-dûr, the flames of Mount Doom, and countless orc armies.',
    'mordor_locations': 'Places of Mordor',
    'mordor_forces': 'Forces of Mordor',
    'mordor_history': 'History of Mordor',
    // Mordor locations
    'barad_dur_name': 'Barad-dûr',
    'barad_dur_desc': 'Sauron\'s dark tower. The heart of Mordor and the center of dark power.',
    'mount_doom_name': 'Mount Doom',
    'mount_doom_desc': 'Orodruin, the only place where the One Ring was forged and can be destroyed.',
    'minas_morgul_mordor_name': 'Minas Morgul',
    'minas_morgul_mordor_desc': 'Former Minas Ithil, now under the control of the Nazgûl. Dark and dangerous.',
    'cirith_ungol_name': 'Cirith Ungol',
    'cirith_ungol_desc': 'Spider Pass, the dangerous passage where Shelob lives.',
    'udun_name': 'Udûn',
    'udun_desc': 'Mordor\'s northern valley, where Sauron\'s armies gather.',
    'gorgoroth_name': 'Gorgoroth',
    'gorgoroth_desc': 'Mordor\'s central plain, dark and barren lands.',
    // Mordor forces
    'orcs_title': 'Orcs',
    'orcs_desc': 'Sauron\'s main army. Dark and savage warriors.',
    'nazgul_title': 'Nazgûl',
    'nazgul_desc': 'The Nine Ring-bearers, Sauron\'s most powerful servants.',
    'trolls_title': 'Trolls',
    'trolls_desc': 'Massive and powerful creatures, part of Sauron\'s war machine.',
    'fellbeasts_title': 'Fellbeasts',
    'fellbeasts_desc': 'Winged creatures that serve as mounts for the Nazgûl.',
    // Mordor history
    'mordor_history_1': 'Mordor was founded by Sauron in the Second Age. This dark kingdom became the center of Sauron\'s power and the most dangerous region in Middle-earth.',
    'mordor_history_2': 'The heart of Mordor is Barad-dûr, Sauron\'s dark tower. This tower is the symbol of Sauron\'s power and was built with the influence of the One Ring.',
    'mordor_history_3': 'Mount Doom (Orodruin) is one of Mordor\'s most important places. This volcano is the only place where the One Ring was forged and can be destroyed. Sauron\'s power spreads from here.',
    'mordor_history_4': 'Mordor was the center of Sauron\'s armies during the War of the Ring. Countless orcs, trolls, and other dark creatures set out from here to threaten Middle-earth.',
    'mordor_history_5': 'Mordor\'s most powerful beings are the Nazgûl. The Nine Ring-bearers are Sauron\'s most powerful servants and spread fear while flying on Fellbeasts.',
    'mordor_history_6': 'Today, Mordor has been largely abandoned after Sauron\'s defeat. However, dark forces still lurk in these lands, and dangerous creatures continue to live here.',
    // Mount Doom page
    'mount_doom_page_title': 'MOUNT DOOM',
    'mount_doom_quote': 'Mount Doom - Where the Ring was Created and Destroyed',
    'mount_doom_quote_author': 'Fire Pit',
    'mount_doom_description': 'Mount Doom is a massive volcano rising in the heart of Mordor. This mountain is the center of Sauron\'s power and where the Ring was created.',
    'mount_doom_history_importance': 'History and Importance',
    'physical_features': 'Physical Features',
    'important_events': 'Important Events',
    'cultural_importance': 'Cultural Importance',
    // Mount Doom history and importance
    'mount_doom_history_1': 'Mount Doom is a massive volcano rising in the heart of Mordor. This mountain is the center of Sauron\'s power and where the Ring was created. The Fire Pit at the mountain\'s summit is the only place where the Ring can be destroyed.',
    'mount_doom_history_2': 'In the Second Age, Sauron made this mountain the center of his power and created the Ring here. The mountain\'s constant lava eruptions and dark atmosphere symbolize Mordor\'s terrifying nature.',
    'mount_doom_history_3': 'During the War of the Ring, Frodo and Sam\'s final mission was to reach this mountain and throw the Ring into the Fire Pit. This journey was the most dangerous mission that would determine the fate of Middle-earth.',
    // Mount Doom physical features
    'mountain_structure_title': 'Mountain Structure',
    'mountain_structure_desc': 'The cone-shaped mountain constantly erupts lava and is surrounded by dark smoke. The crater at the mountain\'s summit contains the Fire Pit where the Ring can be destroyed.',
    'atmosphere_title': 'Atmosphere',
    'atmosphere_desc': 'The area around the mountain is constantly covered with dark clouds. Lava light and smoke give the region a terrifying atmosphere. The air is constantly hot and filled with poisonous gases.',
    'fire_pit_title': 'Fire Pit',
    'fire_pit_desc': 'The crater at the mountain\'s summit is the only place where the Ring was created and can be destroyed. This pit is the source of Sauron\'s power and constantly erupts lava.',
    // Mount Doom important events
    'ring_creation_title': 'Creation of the Ring',
    'ring_creation_desc': 'In the Second Age, Sauron created the One Ring at Mount Doom. This ring was designed to control the other rings of power.',
    'frodo_journey_title': 'Frodo\'s Journey',
    'frodo_journey_desc': 'Frodo and Sam reached Mount Doom to destroy the Ring. This journey was the most dangerous mission that would determine the fate of Middle-earth.',
    'ring_destruction_title': 'Destruction of the Ring',
    'ring_destruction_desc': 'With Gollum\'s intervention, the Ring fell into the Fire Pit and was destroyed. This event completely destroyed Sauron\'s power and ended the Third Age.',
    // Mount Doom cultural importance
    'symbolic_meaning_title': 'Symbolic Meaning',
    'symbolic_meaning_desc_1': 'Mount Doom is a symbol of evil and destruction. The mountain\'s constant lava eruptions represent Sauron\'s ever-increasing power.',
    'symbolic_meaning_desc_2': 'At the same time, it is also a symbol of hope and sacrifice. Frodo\'s ascent to this mountain is the greatest example of good\'s struggle against evil.',
    'literary_importance_title': 'Literary Importance',
    'literary_importance_desc_1': 'In J.R.R. Tolkien\'s works, Mount Doom is portrayed as the center of dark forces. The mountain is the most dangerous and terrifying place in Middle-earth.',
    'literary_importance_desc_2': 'The mountain\'s physical features and atmosphere are designed to make the reader feel the nature of evil.',
    // Helm's Deep page
    'helms_deep_page_title': 'HELM\'S DEEP',
    'helms_deep_quote': 'Helm\'s Deep - Rohan\'s Impregnable Fortress',
    'helms_deep_quote_author': 'Hornburg',
    'helms_deep_description': 'Helm\'s Deep is Rohan\'s strongest fortress. This impregnable castle, located at the foothills of the White Mountains, is Rohan\'s last line of defense and has witnessed many great battles in history.',
    'history_and_importance_helms': 'History and Importance',
    'great_battle': 'Great Battle',
    'fortress_features': 'Fortress Features',
    'battle_heroes': 'Battle Heroes',
    // Helm's Deep history and importance
    'helms_deep_history_1': 'Helm\'s Deep is Rohan\'s strongest fortress located in the White Mountains. This fortress protects Rohan\'s eastern border and is the last line of defense against enemy attacks.',
    'helms_deep_history_2': 'The fortress was built by Helm Hammerhand, Rohan\'s old king. The fortress gets its name from him. Built on the natural cliffs of the White Mountains, the fortress has an impregnable structure.',
    'helms_deep_history_3': 'During the War of the Ring, Helm\'s Deep became Rohan\'s last hope. This battle against Saruman\'s armies became one of the most important battles that would determine the fate of Middle-earth.',
    // Helm's Deep battle
    'battle_of_helms_deep': 'Battle of Helm\'s Deep',
    'battle_start_title': 'Beginning of the Battle',
    'battle_start_desc': 'Saruman\'s army of 10,000 orcs attacked Helm\'s Deep to invade Rohan. Rohan\'s king Théoden was forced to take refuge in this fortress.',
    'defense_title': 'Defense',
    'defense_desc': 'The defense, which included Aragorn, Legolas, and Gimli, lasted throughout the night. The orcs tried to breach the fortress walls, but Rohan\'s warriors heroically resisted.',
    'gandalf_arrival_title': 'Gandalf\'s Arrival',
    'gandalf_arrival_desc': 'At dawn, Gandalf arrived with Éomer. The orcs scattered in the sunlight and Rohan won the victory. This battle played an important role in breaking Saruman\'s power.',
    // Helm's Deep fortress features
    'hornburg_title': 'Hornburg',
    'hornburg_desc': 'Hornburg, the main tower of the fortress, is located at the highest point of the White Mountains. This tower is in a perfect position to observe enemy movements.',
    'deeping_wall_title': 'Deeping Wall',
    'deeping_wall_desc': 'Deeping Wall, the main defensive wall of the fortress, is 20 meters high and has an impregnable structure. There are special positions for archers on the wall.',
    'deeping_coomb_title': 'Deeping Coomb',
    'deeping_coomb_desc': 'Deeping Coomb, the valley in front of the fortress, limits enemy armies and creates a natural barrier for defense. This valley is where the orcs gathered during the battle.',
    // Helm's Deep heroes
    'aragorn_hero_title': 'Aragorn',
    'aragorn_hero_desc_1': 'He led Rohan\'s defense during the battle. His courage and leadership played a major role in the struggle against the orcs.',
    'aragorn_hero_quote': 'We fought all night, but victory was ours at dawn.',
    'legolas_gimli_title': 'Legolas and Gimli',
    'legolas_gimli_desc_1': 'The most beautiful example of elf and dwarf friendship. They fought together during the battle and protected each other.',
    'legolas_gimli_desc_2': 'There was a friendly competition between the number of orcs Gimli killed and the number of targets Legolas shot with his arrows.',
    'map_title': 'Middle-earth Map',
    'map_subtitle': 'Explore the magical lands',
    'shop_title': 'Our Products',
    'shop_subtitle': 'Special products from Middle-earth',
    'view_all': 'View All',
    'add_to_cart': 'Add to Cart',
    'price': 'Price',
    'category': 'Category',
    // Shop kategorileri
    'rings': 'Rings',
    'swords': 'Swords',
    'cloaks': 'Cloaks',
    'maps': 'Maps',
    'figures': 'Figures',
    'elf_jewelry': 'Elf Jewelry',
    'books': 'Middle-earth Books',
    'hobbit_items': 'Hobbit Items',
    'elf_bows': 'Elf Bows',
    'dwarf_axes': 'Dwarf Axes',
    'nazgul_masks': 'Nazgûl Masks',
    'orc_armors': 'Orc Armors',
    'wizard_staffs': 'Wizard Staffs',
    'gondor_helmets': 'Gondor Helmets',
    'rohan_horses': 'Rohan Horse Figures',
    'posters': 'Middle-earth Posters',
    'cards': 'Collection Cards',
    'collection_figures': 'Collection Figures',
    'home_office': 'Home & Office',
    'accessories': 'Accessories & Jewelry',
    'clothes': 'Clothes',
    'games_puzzles': 'Games & Puzzles',
    'kitchen': 'Kitchen',
    'coins_replicas': 'Coins & Replicas',
    'plush_toys': 'Plush & Toys',
    // Shop butonları
    'buy_now': 'Buy Now',
    'checkout': 'Checkout',
    'cart_summary': 'Your Cart',
    'no_cart_items': 'Your cart is empty.',
    'total': 'Total',
    'product': 'Product',
    'quantity': 'Quantity',
    'action': 'Action',
    'remove_from_cart': 'Remove from Cart',
    'continue_shopping': 'Continue Shopping',
    'card_info': 'Card Information',
    'card_name_placeholder': 'Name on Card',
    'card_number_placeholder': 'Card Number',
    'expiry_placeholder': 'MM/YY',
    'cvc_placeholder': 'CVC',
    'email_placeholder': 'Email',
    'address_placeholder': 'Shipping Address',
    'complete_payment': 'Complete Payment',
    'payment_success': 'Payment Successful!',
    'payment_success_desc': 'Your order has been received, welcome to Middle-earth! 🧙‍♂️',
    'go_home': 'Return to Home',
    // Profil menüsü
    'orders_title': 'My Orders',
    'order_number': 'Order',
    'order_date': 'Date',
    'order_status_delivered': 'Delivered',
    'order_status_shipping': 'Shipped',
    'order_status_preparing': 'Preparing',
    'order_status_cancelled': 'Cancelled',
    'order_status_pending': 'Pending',
    'delivery_address': 'Delivery Address',
    'total_amount': 'Total Amount',
    'ordered_products': 'Ordered Products',
    'order_loading': 'Loading...',
    'order_none': 'You have no orders yet.',
    'order_first_cta': 'To place your first order,',
    'order_first_link': 'check our products',
    'order_first_end': '.',
    'order_product_none': 'No product information found.',
    'currency_try': '₺',
    'currency_usd': '$',
    'requests_title': 'Questions & Requests',
    'requests_help_title': 'How can we help you?',
    'requests_help_sub': 'You can send your questions and requests here.',
    'select_category': 'Select category',
    'category_product': 'Product Info',
    'category_order': 'Order Status',
    'category_return': 'Return/Exchange',
    'category_technical': 'Technical Support',
    'category_suggestion': 'Suggestion/Complaint',
    'category_other': 'Other',
    'subject_placeholder': 'Subject of your message',
    'priority_low': 'Low',
    'priority_normal': 'Normal',
    'priority_high': 'High',
    'priority_urgent': 'Urgent',
    'message_placeholder': 'Write your detailed message here...',
    'send_message': 'Send Message',
    'sending': 'Sending...',
    'contact_info': 'Contact Information',
    'work_hours': 'Working Hours',
    'past_requests': 'Your Past Requests',
    'no_requests': 'You have no questions or requests yet.',
    'topic': 'Topic',
    'your_message': 'Your Message',
    'reply': 'Reply',
    'pending': 'Pending',
    'answered': 'Answered',
    'required_fields': 'Please fill in all required fields.',
    'user_not_found': 'User not found.',
    'db_error': 'Could not connect to Firestore.',
    'send_success': 'Your message has been sent successfully! We will get back to you as soon as possible.',
    'send_error': 'An error occurred. Please try again.',
    // --- OFFERS PAGE ---
    'loading': 'Loading...',
    'no_offers': 'There are no special offers for you at the moment.',
    'follow_for_offers': 'Keep following us for new offers!',
    'coupon_code': 'Coupon Code',
    'expiry_date': 'Expiry Date',
    'min_amount': 'Minimum Amount',
    'start_shopping': 'Start Shopping',
    'copy_code': 'Copy Code',
    'offers_email_tip': 'Don\'t forget to enable email notifications to not miss any offers!',
    'discount': 'Discount',
    'shipping': 'Shipping',
    'gift': 'Gift',
    'offer': 'Offer',
    // --- PROFILE PAGE ---
    'profile_tab_info': 'Membership Info',
    'profile_tab_password': 'Change Password',
    'profile_tab_prefs': 'Contact Preferences',
    'profile_tab_addresses': 'My Addresses',
    'profile_tab_update': 'Update Info',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'birth_date': 'Birth Date',
    'gender_select': 'Gender (select)',
    'gender_male': 'Male',
    'gender_female': 'Female',
    'gender_other': 'Other',
    'phone_number': 'Phone Number',
    'email_address': 'Email Address',
    'profile_info_note': 'Info can only be filled during registration. Use the "Update Info" tab to update.',
    'address_title': 'Address Title',
    'country_turkey': 'Turkey',
    'city': 'City',
    'district': 'District',
    'address_detail': 'Full Address',
    'add': 'Add',
    'adding': 'Adding...',
    'saved_addresses': 'Saved Addresses:',
    'no_addresses': 'You have not added any address yet.',
    'delete': 'Delete',
    'password': 'Password',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'checking': 'Checking...',
    'continue': 'Continue',
    'update': 'Update',
    'updating': 'Updating...',
    'verifying': 'Verifying...',
    'save': 'Save',
    'saving': 'Saving...',
    'sms_channel': 'SMS Channels',
    'email_channel': 'E-mail',
    'phone_channel': 'Phone Call',
    
    // Galadriel page
    'galadriel_page_title': 'Galadriel',
    'galadriel_quote': 'Queen of Lothlórien - Bearer of Nenya',
    'galadriel_quote_author': 'Wife of Celeborn',
    'galadriel_description': 'Galadriel is the most powerful elf woman in Middle-earth. As the queen of Lothlórien, she is the bearer of the Ring Nenya and one of the last Noldor from Valinor.',
    'history_and_importance': 'History and Importance',
    'power_and_magic': 'Power and Magic',
    // Galadriel history
    'galadriel_history_1': 'Galadriel is one of the last Noldor who came from Valinor to Middle-earth. She participated in Fëanor\'s rebellion and left Valinor. She has lived in Middle-earth for thousands of years.',
    'galadriel_history_2': 'In the Second Age, Galadriel and her husband Celeborn founded Lothlórien. This kingdom became one of the most beautiful and mysterious places in Middle-earth.',
    'galadriel_history_3': 'Galadriel is the bearer of the Ring Nenya. This ring protects Lothlórien and slows the effects of time. Galadriel\'s power is used for the safety of her kingdom.',
    // Galadriel powers
    'nenya_ring_title': 'Ring of Nenya',
    'nenya_ring_desc': 'Galadriel bears the Ring Nenya. This ring protects Lothlórien and slows the effects of time. The ring is made of water and diamond stone.',
    'magic_power_title': 'Magic Power',
    'magic_power_desc': 'Galadriel is the most powerful elf woman in Middle-earth. She has the ability to see the future and frighten her enemies with her magic power.',
    'lothlorien_protector_title': 'Protector of Lothlórien',
    'lothlorien_protector_desc': 'Galadriel\'s power protects Lothlórien. The kingdom remains hidden and safe thanks to her magic. Enemies cannot enter the kingdom.',
    // Important events
    'important_events_title': 'Important Events',
    'departure_from_valinor_title': 'Departure from Valinor',
    'departure_from_valinor_desc': 'Galadriel left Valinor by participating in Fëanor\'s rebellion. She came to Middle-earth and lived here for thousands of years.',
    'lothlorien_foundation_title': 'Foundation of Lothlórien',
    'lothlorien_foundation_desc': 'In the Second Age, Galadriel and Celeborn founded Lothlórien. This kingdom became one of the most beautiful places in Middle-earth.',
    'fellowship_hosting_title': 'Fellowship of the Ring',
    'fellowship_hosting_desc': 'Galadriel hosted the Fellowship of the Ring in Lothlórien. She gave them gifts and helped them continue their journey.',
    // Lothlórien
    'lothlorien_title': 'Lothlórien',
    'golden_forest_title': 'Golden Forest',
    'golden_forest_desc_1': 'Lothlórien is a golden forest covered with mallorn trees. These trees always shine with golden leaves thanks to Galadriel\'s magic.',
    'golden_forest_desc_2': 'The forest is protected from the effects of time and is a safe haven for the elves living within it.',
    'caras_galadhon_title': 'Caras Galadhon',
    'caras_galadhon_desc_1': 'Caras Galadhon, the capital of Lothlórien, is a city built on mallorn trees. Galadriel and Celeborn live here and rule the kingdom.',
    'caras_galadhon_desc_2': 'The city remains hidden thanks to Galadriel\'s magic and cannot be seen by enemies.',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('tr');

  useEffect(() => {
    // LocalStorage'dan dil tercihini al
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'tr' || savedLanguage === 'en')) {
        setLanguageState(savedLanguage);
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
      // HTML lang attribute'unu güncelle
      document.documentElement.lang = lang;
    }
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
} 